// 页面：答题闯关（题目卡 / 选项 / 教练 / 道具背包 / 即时讲解）
import { knowledgeName } from '../questions';
import { CorrectEffect, RelicInventory, VideoBtn, VisualSVG } from './bits';

function GameView({ q, index, questionCount, level, gameMode, subject, profileGrade, lives, streak, stars, answerState, message, activeRelics, relicUses, passiveState, armedEffects, hiddenOptions, revealedAnswer, onUseRelic, onAnswer, onBack, onRead, onReadExplain, onAskAI }) {
  const keys = ['A', 'B', 'C', 'D'];
  return <section className={`screen active ${answerState?.isCorrect ? 'correct-hit' : ''}`} id="screen-game"><div className="game-shell"><div className="game-topbar"><button className="icon-btn" onClick={onBack}>←</button><div className="game-identity"><span>{subject.emoji}</span><div><b>{subject.name}岛{q.aiMade ? ' · AI专属' : ''}{gameMode === '错题重练' ? ' · 错题重练' : ''}</b><small>第 {level} / 5 层 · {knowledgeName(subject.id, q.knowledge)}</small></div></div><div className="game-stats"><div><span>❤️</span><b>{'❤️'.repeat(lives) || '0'}</b><small>生命</small></div><div><span>🔥</span><b>{streak}</b><small>连对</small></div><div><span>⭐</span><b>{stars}</b><small>星星</small></div></div></div><div className="progress-area"><div className="progress-meta"><span>第 {index + 1} / {questionCount} 题</span><span>{Math.round(index / questionCount * 100)}%</span></div><div className="progress-track"><div id="progress-fill" style={{ width: `${index / questionCount * 100}%` }} /><span id="progress-dog" style={{ left: `${index / questionCount * 100}%` }}>🐾</span></div></div><div className="game-content"><aside className="coach-card"><div className={`coach-mascot ${answerState?.isCorrect ? 'happy' : ''}`}>🐶</div><div className="coach-bubble">{message}</div><RelicInventory relics={activeRelics} relicUses={relicUses} passiveState={passiveState} armedEffects={armedEffects} lives={lives} streak={streak} index={index} questionCount={questionCount} answerState={answerState} hiddenOptions={hiddenOptions} revealedAnswer={revealedAnswer} onUse={onUseRelic} /></aside><div className="quiz-column">{answerState?.isCorrect && <CorrectEffect key={`${q.id}-${index}`} streak={streak} earnedStars={answerState.earnedStars} />}<article className="question-card"><div className="question-header"><span className="type-tag">{q.type}{q.review ? ' · 待复习' : ''}</span><button className="read-btn" onClick={onRead}>🔈 读题</button></div><h2>{q.prompt}</h2><div className="question-extra">{q.svg ? <VisualSVG spec={q.svg} /> : <div className="visual-word">{q.visual}</div>}</div><p className="question-hint">{revealedAnswer ? '水晶正在提示正确答案' : '选出你认为正确的答案'}</p></article><div className="answers">{q.options.map((option, i) => {
    const isAnswer = String(option) === String(q.answer);
    const isPicked = answerState && String(option) === String(answerState.value);
    const eliminated = hiddenOptions.some((h) => String(h) === String(option));
    const revealed = revealedAnswer && isAnswer;
    return <button key={`${option}-${i}`} className={`answer ${answerState ? 'disabled' : ''} ${answerState && isAnswer ? 'correct' : ''} ${isPicked && !answerState?.isCorrect ? 'wrong' : ''} ${eliminated ? 'eliminated' : ''} ${revealed ? 'revealed' : ''}`} disabled={Boolean(answerState) || eliminated} onClick={() => onAnswer(option)}><span className="option-key">{keys[i] || ''}</span>{option}</button>;
  })}</div>
  {answerState && !answerState.isCorrect && q.explain && <div className="explain-card"><div className="explain-title">🧑‍🏫 小老师讲题 · {knowledgeName(subject.id, q.knowledge)}</div><p>{q.explain}</p><div className="explain-actions"><button className="secondary-btn" onClick={onReadExplain}>🔈 听讲解</button><button className="secondary-btn" onClick={onAskAI}>🤖 问AI老师</button><VideoBtn grade={profileGrade} unit={knowledgeName(subject.id, q.knowledge)} /></div></div>}
  </div></div></div></section>;
}

export default GameView;
