// 人教版一二年级考纲对齐的知识体系 + 精选题库
// 学科覆盖:数学 / 语文 / 英语(启蒙,PEP三年级起点前置) / 科学 / 生活(道德与法治+健康安全) / 地理常识
// 每题字段: k 知识点, t 题型, p 题干, v 配图/辅助, a 答案, o 选项, e 儿童版讲解

export const KNOWLEDGE = {
  math: [
    { id: 'm-count', name: '数的认识', grade: '一上·一下', desc: '20以内 / 100以内 / 万以内数的读写与组成' },
    { id: 'm-add20', name: '20以内加减法', grade: '一上·一下', desc: '进位加 / 退位减 / 口算' },
    { id: 'm-add100', name: '100以内加减法', grade: '一下·二上', desc: '整十加减 / 两位数加减 / 竖式' },
    { id: 'm-mult', name: '表内乘法', grade: '二上', desc: '乘法口诀 / 乘法含义' },
    { id: 'm-div', name: '平均分与除法', grade: '二下', desc: '平均分 / 除法含义 / 口诀求商' },
    { id: 'm-length', name: '长度单位', grade: '二上', desc: '厘米 / 米 / 线段 / 测量' },
    { id: 'm-angle', name: '角的初步认识', grade: '二上', desc: '角 / 直角 / 锐角钝角' },
    { id: 'm-time', name: '认识钟表时间', grade: '一上·二上', desc: '整时 / 半时 / 几时几分' },
    { id: 'm-money', name: '认识人民币', grade: '一下', desc: '元角分 / 换算 / 简单计算' },
    { id: 'm-shape', name: '图形与观察', grade: '一上·一下·二上', desc: '立体图形 / 平面图形 / 观察物体' },
    { id: 'm-pattern', name: '找规律排序', grade: '一下', desc: '数字规律 / 图形规律 / 排列' },
    { id: 'm-word', name: '解决问题', grade: '全册', desc: '看图列式 / 生活应用题' },
    { id: 'm-mult2', name: '多位数与运算定律', grade: '三~四年级', desc: '两三位数乘除 / 估算 / 加乘运算定律' },
    { id: 'm-frac', name: '分数', grade: '三~五年级', desc: '分数含义 / 比较 / 同分母加减 / 真假带分数' },
    { id: 'm-dec', name: '小数', grade: '三~四年级', desc: '小数的读写 / 比较 / 简单加减' },
    { id: 'm-area', name: '图形与几何', grade: '三~六年级', desc: '周长面积 / 长方体正方体 / 圆 / 位置方向' },
    { id: 'm-eq', name: '简易方程', grade: '五年级', desc: '用字母表示数 / 解方程 / 列方程解题' },
    { id: 'm-ratio', name: '比·比例·百分数', grade: '六年级', desc: '比的含义 / 比例尺 / 百分数 / 折扣税率' },
    { id: 'm-stat', name: '统计与概率', grade: '五~六年级', desc: '条形折线扇形图 / 平均数 / 可能性' },
    // ---- 人教版数学 1-6 年级上下册单元目录（跳过总复习）----
    { id: 'math-1a-01', name: '准备课', grade: '一年级上', desc: '数一数 / 比多少' },
    { id: 'math-1a-02', name: '位置', grade: '一年级上', desc: '上、下、前、后、左、右' },
    { id: 'math-1a-03', name: '1～5的认识和加减法', grade: '一年级上', desc: '数的认识 / 比大小 / 分与合 / 加减含义' },
    { id: 'math-1a-04', name: '认识图形（一）', grade: '一年级上', desc: '长方体 / 正方体 / 圆柱 / 球' },
    { id: 'math-1a-05', name: '6～10的认识和加减法', grade: '一年级上', desc: '6-10各数 / 10以内加减 / 连加连减加减混合' },
    { id: 'math-1a-06', name: '11～20各数的认识', grade: '一年级上', desc: '数数读数 / 数的组成 / 10加几' },
    { id: 'math-1a-07', name: '认识钟表', grade: '一年级上', desc: '整时 / 半时' },
    { id: 'math-1a-08', name: '20以内的进位加法', grade: '一年级上', desc: '9加几 / 8、7、6加几 / 凑十法' },
    { id: 'math-1b-01', name: '认识图形（二）', grade: '一年级下', desc: '长方形 / 正方形 / 三角形 / 圆 / 拼组' },
    { id: 'math-1b-02', name: '20以内的退位减法', grade: '一年级下', desc: '十几减9 / 十几减几 / 破十法' },
    { id: 'math-1b-03', name: '分类与整理', grade: '一年级下', desc: '单一标准 / 不同标准分类' },
    { id: 'math-1b-04', name: '100以内数的认识', grade: '一年级下', desc: '数数 / 读写 / 组成 / 比较大小' },
    { id: 'math-1b-05', name: '认识人民币', grade: '一年级下', desc: '元角分 / 换算 / 简单计算' },
    { id: 'math-1b-06', name: '100以内的加法和减法（一）', grade: '一年级下', desc: '整十加减 / 两位数加减一位数整十数' },
    { id: 'math-1b-07', name: '找规律', grade: '一年级下', desc: '图形规律 / 数字规律' },
    { id: 'math-2a-01', name: '长度单位', grade: '二年级上', desc: '厘米 / 米 / 线段 / 测量' },
    { id: 'math-2a-02', name: '100以内的加法（二）', grade: '二年级上', desc: '不进位加 / 进位加 / 退位减 / 连加连减' },
    { id: 'math-2a-03', name: '角的初步认识', grade: '二年级上', desc: '角 / 直角 / 锐角钝角' },
    { id: 'math-2a-04', name: '表内乘法（一）', grade: '二年级上', desc: '乘法含义 / 2-6的口诀' },
    { id: 'math-2a-05', name: '观察物体（一）', grade: '二年级上', desc: '前后左右看 / 对称' },
    { id: 'math-2a-06', name: '表内乘法（二）', grade: '二年级上', desc: '7-9的口诀 / 解决问题' },
    { id: 'math-2a-07', name: '认识时间', grade: '二年级上', desc: '几时几分 / 时间推算' },
    { id: 'math-2a-08', name: '数学广角——搭配（一）', grade: '二年级上', desc: '简单排列组合' },
    { id: 'math-2b-01', name: '数据收集整理', grade: '二年级下', desc: '调查记录 / 简单统计表' },
    { id: 'math-2b-02', name: '表内除法（一）', grade: '二年级下', desc: '平均分 / 除法含义 / 2-6口诀求商' },
    { id: 'math-2b-03', name: '图形的运动（一）', grade: '二年级下', desc: '对称 / 平移 / 旋转' },
    { id: 'math-2b-04', name: '表内除法（二）', grade: '二年级下', desc: '7-9口诀求商 / 解决问题' },
    { id: 'math-2b-05', name: '混合运算', grade: '二年级下', desc: '同级 / 两级 / 带小括号' },
    { id: 'math-2b-06', name: '有余数的除法', grade: '二年级下', desc: '余数含义 / 试商' },
    { id: 'math-2b-07', name: '万以内数的认识', grade: '二年级下', desc: '千 / 万 / 读写组成 / 近似数' },
    { id: 'math-2b-08', name: '克和千克', grade: '二年级下', desc: '质量单位 / 估计' },
    { id: 'math-2b-09', name: '数学广角——推理', grade: '二年级下', desc: '简单逻辑推理' },
    { id: 'math-3a-01', name: '时、分、秒', grade: '三年级上', desc: '秒的认识 / 时间计算' },
    { id: 'math-3a-02', name: '万以内的加法和减法（一）', grade: '三年级上', desc: '两位数加减 / 估算' },
    { id: 'math-3a-03', name: '测量', grade: '三年级上', desc: '毫米分米 / 千米 / 吨' },
    { id: 'math-3a-04', name: '万以内的加法和减法（二）', grade: '三年级上', desc: '三位数加减 / 验算' },
    { id: 'math-3a-05', name: '倍的认识', grade: '三年级上', desc: '倍的含义 / 求倍数' },
    { id: 'math-3a-06', name: '多位数乘一位数', grade: '三年级上', desc: '口算 / 笔算 / 解决问题' },
    { id: 'math-3a-07', name: '长方形和正方形', grade: '三年级上', desc: '四边形 / 周长' },
    { id: 'math-3a-08', name: '分数的初步认识', grade: '三年级上', desc: '几分之一 / 几分之几 / 比较 / 简单加减' },
    { id: 'math-3a-09', name: '数学广角——集合', grade: '三年级上', desc: '重叠问题' },
    { id: 'math-3b-01', name: '位置与方向（一）', grade: '三年级下', desc: '东南西北 / 地图方向 / 路线图' },
    { id: 'math-3b-02', name: '除数是一位数的除法', grade: '三年级下', desc: '口算 / 笔算 / 验算' },
    { id: 'math-3b-03', name: '复式统计表', grade: '三年级下', desc: '复式统计 / 分析数据' },
    { id: 'math-3b-04', name: '两位数乘两位数', grade: '三年级下', desc: '口算 / 笔算' },
    { id: 'math-3b-05', name: '面积', grade: '三年级下', desc: '面积含义 / 单位 / 长正方形面积' },
    { id: 'math-3b-06', name: '年、月、日', grade: '三年级下', desc: '年月日 / 平闰年 / 24时计时' },
    { id: 'math-3b-07', name: '小数的初步认识', grade: '三年级下', desc: '小数的读写 / 比较 / 简单加减' },
    { id: 'math-3b-08', name: '数学广角——搭配（二）', grade: '三年级下', desc: '搭配 / 有序思考' },
    { id: 'math-4a-01', name: '大数的认识', grade: '四年级上', desc: '亿以内 / 亿以上 / 近似数' },
    { id: 'math-4a-02', name: '公顷和平方千米', grade: '四年级上', desc: '大面积单位 / 换算' },
    { id: 'math-4a-03', name: '角的度量', grade: '四年级上', desc: '直线射线 / 角 / 量角画角' },
    { id: 'math-4a-04', name: '三位数乘两位数', grade: '四年级上', desc: '笔算 / 积的变化规律' },
    { id: 'math-4a-05', name: '平行四边形和梯形', grade: '四年级上', desc: '垂直平行 / 高 / 分类' },
    { id: 'math-4a-06', name: '除数是两位数的除法', grade: '四年级上', desc: '口算 / 笔算试商 / 商的变化规律' },
    { id: 'math-4a-07', name: '条形统计图', grade: '四年级上', desc: '1格多单位 / 优化' },
    { id: 'math-4a-08', name: '数学广角——优化', grade: '四年级上', desc: '沏茶烙饼 / 田忌赛马' },
    { id: 'math-4b-01', name: '四则运算', grade: '四年级下', desc: '加减乘除意义 / 括号 / 解决问题' },
    { id: 'math-4b-02', name: '观察物体（二）', grade: '四年级下', desc: '三视图 / 拼搭' },
    { id: 'math-4b-03', name: '运算定律', grade: '四年级下', desc: '加法交换结合 / 乘法交换结合分配 / 简便计算' },
    { id: 'math-4b-04', name: '小数的意义和性质', grade: '四年级下', desc: '小数意义 / 读写 / 性质 / 大小比较 / 改写求近似' },
    { id: 'math-4b-05', name: '三角形', grade: '四年级下', desc: '特性 / 分类 / 内角和' },
    { id: 'math-4b-06', name: '小数的加法和减法', grade: '四年级下', desc: '小数加减笔算 / 混合运算' },
    { id: 'math-4b-07', name: '图形的运动（二）', grade: '四年级下', desc: '轴对称 / 平移' },
    { id: 'math-4b-08', name: '平均数与条形统计图', grade: '四年级下', desc: '平均数 / 复式条形图' },
    { id: 'math-4b-09', name: '数学广角——鸡兔同笼', grade: '四年级下', desc: '列表 / 假设法' },
    { id: 'math-5a-01', name: '小数乘法', grade: '五年级上', desc: '小数乘整数 / 小数乘小数 / 积的近似数' },
    { id: 'math-5a-02', name: '位置', grade: '五年级上', desc: '数对 / 确定位置' },
    { id: 'math-5a-03', name: '小数除法', grade: '五年级上', desc: '除数整数小数 / 商的近似数 / 循环小数' },
    { id: 'math-5a-04', name: '可能性', grade: '五年级上', desc: '可能 / 一定 / 掷一掷' },
    { id: 'math-5a-05', name: '简易方程', grade: '五年级上', desc: '用字母表示数 / 解方程 / 实际问题与方程' },
    { id: 'math-5a-06', name: '多边形的面积', grade: '五年级上', desc: '平行四边形 / 三角形 / 梯形 / 组合图形' },
    { id: 'math-5a-07', name: '数学广角——植树问题', grade: '五年级上', desc: '两端都栽 / 封闭路线' },
    { id: 'math-5b-01', name: '观察物体（三）', grade: '五年级下', desc: '三视图摆搭' },
    { id: 'math-5b-02', name: '因数与倍数', grade: '五年级下', desc: '因数倍数 / 2、3、5的倍数特征 / 质数合数' },
    { id: 'math-5b-03', name: '长方体和正方体', grade: '五年级下', desc: '认识 / 表面积 / 体积容积' },
    { id: 'math-5b-04', name: '分数的意义和性质', grade: '五年级下', desc: '分数意义 / 真假分数 / 基本性质 / 约分通分' },
    { id: 'math-5b-05', name: '图形的运动（三）', grade: '五年级下', desc: '旋转 / 设计图案' },
    { id: 'math-5b-06', name: '分数的加法和减法', grade: '五年级下', desc: '同分母 / 异分母 / 分数加减混合' },
    { id: 'math-5b-07', name: '折线统计图', grade: '五年级下', desc: '单式复式 / 分析趋势' },
    { id: 'math-5b-08', name: '数学广角——找次品', grade: '五年级下', desc: '优化策略' },
    { id: 'math-6a-01', name: '分数乘法', grade: '六年级上', desc: '分数乘整数分数 / 解决问题' },
    { id: 'math-6a-02', name: '位置与方向（二）', grade: '六年级上', desc: '方向距离 / 路线图' },
    { id: 'math-6a-03', name: '分数除法', grade: '六年级上', desc: '倒数 / 分数除法 / 解决问题' },
    { id: 'math-6a-04', name: '比', grade: '六年级上', desc: '比的意义性质 / 按比分配' },
    { id: 'math-6a-05', name: '圆', grade: '六年级上', desc: '认识 / 周长 / 面积 / 扇形' },
    { id: 'math-6a-06', name: '百分数（一）', grade: '六年级上', desc: '百分数意义读写 / 小数分数百分数互化' },
    { id: 'math-6a-07', name: '扇形统计图', grade: '六年级上', desc: '扇形图 / 选择合适统计图' },
    { id: 'math-6a-08', name: '数学广角——数与形', grade: '六年级上', desc: '数形结合找规律' },
    { id: 'math-6b-01', name: '负数', grade: '六年级下', desc: '正负数 / 数轴' },
    { id: 'math-6b-02', name: '百分数（二）', grade: '六年级下', desc: '折扣 / 成数 / 税率 / 利率' },
    { id: 'math-6b-03', name: '圆柱与圆锥', grade: '六年级下', desc: '认识 / 表面积 / 体积' },
    { id: 'math-6b-04', name: '比例', grade: '六年级下', desc: '比例意义性质 / 正反比例 / 比例尺 / 图形放大缩小' },
    { id: 'math-6b-05', name: '数学广角——鸽巢问题', grade: '六年级下', desc: '抽屉原理' },
  ],
  chinese: [
    { id: 'c-pinyin', name: '汉语拼音', grade: '一上', desc: '声母 / 韵母 / 整体认读 / 拼读' },
    { id: 'c-hanzi', name: '识字与写字', grade: '一上·一下', desc: '笔画笔顺 / 偏旁 / 结构' },
    { id: 'c-words', name: '词语积累', grade: '一下·二上', desc: '组词 / 量词 / 反义词近义词 / 搭配' },
    { id: 'c-sentence', name: '句子与标点', grade: '一下·二上', desc: '句号问号感叹号 / 把被字句 / 比喻句' },
    { id: 'c-read', name: '阅读理解', grade: '二上', desc: '读短文找答案 / 排序 / 古诗' },
    { id: 'c-speak', name: '口语交际与写话', grade: '一下·二上', desc: '看图说话 / 写话 / 礼貌表达' },
    { id: 'c-dict', name: '查字典', grade: '三年级', desc: '音序查字 / 部首查字 / 笔画数' },
    { id: 'c-rhet', name: '修辞手法', grade: '三~五年级', desc: '比喻拟人 / 排比夸张 / 设问反问' },
    { id: 'c-grammar', name: '句子加工', grade: '三~六年级', desc: '扩句缩句 / 修改病句 / 关联词 / 转述句' },
    { id: 'c-read2', name: '现代文阅读', grade: '四~六年级', desc: '分段概括 / 体会含义 / 表达方法' },
    { id: 'c-poem', name: '古诗文', grade: '三~六年级', desc: '必背古诗 / 诗句理解 / 小古文' },
    { id: 'c-write', name: '习作', grade: '三~六年级', desc: '审题选材 / 开头结尾 / 写人记事状物' },
    // ---- 部编版语文 1-6 年级上下册单元目录（含习作/口语交际，跳过纯复习园地）----
    { id: 'yuwen-1a-01', name: '入学教育', grade: '一年级上', desc: '我是中国人 / 我是小学生' },
    { id: 'yuwen-1a-02', name: '汉语拼音', grade: '一年级上', desc: '声母 / 韵母 / 整体认读音节 / 拼读' },
    { id: 'yuwen-1a-03', name: '识字（一）', grade: '一年级上', desc: '天地人 / 金木水火土 / 口耳目 / 日月水火' },
    { id: 'yuwen-1a-04', name: '课文（一）', grade: '一年级上', desc: '秋天 / 小小的船 / 江南 / 四季' },
    { id: 'yuwen-1a-05', name: '识字（二）', grade: '一年级上', desc: '画 / 大小多少 / 小书包 / 日月明 / 升国旗' },
    { id: 'yuwen-1a-06', name: '课文（二）', grade: '一年级上', desc: '影子 / 比尾巴 / 青蛙写诗 / 雨点儿' },
    { id: 'yuwen-1a-07', name: '口语交际', grade: '一年级上', desc: '用多大的声音 / 小兔运南瓜' },
    { id: 'yuwen-1b-01', name: '识字', grade: '一年级下', desc: '春夏秋冬 / 姓氏歌 / 小青蛙 / 猜字谜' },
    { id: 'yuwen-1b-02', name: '课文（一）', grade: '一年级下', desc: '吃水不忘挖井人 / 我多想去看看 / 一个接一个 / 四个太阳' },
    { id: 'yuwen-1b-03', name: '课文（二）', grade: '一年级下', desc: '小公鸡和小鸭子 / 树和喜鹊 / 怎么都快乐' },
    { id: 'yuwen-1b-04', name: '课文（三）', grade: '一年级下', desc: '静夜思 / 夜色 / 端午粽 / 彩虹' },
    { id: 'yuwen-1b-05', name: '课文（四）', grade: '一年级下', desc: '动物儿歌 / 古对今 / 操场上 / 人之初' },
    { id: 'yuwen-1b-06', name: '口语交际', grade: '一年级下', desc: '听故事讲故事 / 请你帮个忙' },
    { id: 'yuwen-2a-01', name: '课文（一）', grade: '二年级上', desc: '小蝌蚪找妈妈 / 我是什么 / 植物妈妈有办法' },
    { id: 'yuwen-2a-02', name: '课文（二）', grade: '二年级上', desc: '古诗二首 / 黄山奇石 / 日月潭 / 葡萄沟' },
    { id: 'yuwen-2a-03', name: '课文（三）', grade: '二年级上', desc: '坐井观天 / 寒号鸟 / 我要的是葫芦' },
    { id: 'yuwen-2a-04', name: '课文（四）', grade: '二年级上', desc: '大禹治水 / 朱德的扁担 / 难忘的泼水节' },
    { id: 'yuwen-2a-05', name: '课文（五）', grade: '二年级上', desc: '古诗二首 / 雾在哪里 / 雪孩子' },
    { id: 'yuwen-2a-06', name: '课文（六）', grade: '二年级上', desc: '狐假虎威 / 狐狸分奶酪 / 狐狸养鸡' },
    { id: 'yuwen-2a-07', name: '课文（七）', grade: '二年级上', desc: '纸船和风筝 / 风娃娃' },
    { id: 'yuwen-2a-08', name: '口语交际', grade: '二年级上', desc: '做手工 / 商量 / 看图讲故事' },
    { id: 'yuwen-2b-01', name: '课文（一）', grade: '二年级下', desc: '古诗二首 / 找春天 / 开满鲜花的小路' },
    { id: 'yuwen-2b-02', name: '课文（二）', grade: '二年级下', desc: '雷锋叔叔 / 千人糕 / 一匹出色的马' },
    { id: 'yuwen-2b-03', name: '识字', grade: '二年级下', desc: '神州谣 / 传统节日 / 贝的故事 / 中国美食' },
    { id: 'yuwen-2b-04', name: '课文（三）', grade: '二年级下', desc: '彩色的梦 / 枫树上的喜鹊 / 沙滩上的童话 / 我是一只小虫子' },
    { id: 'yuwen-2b-05', name: '课文（四）', grade: '二年级下', desc: '寓言二则 / 画杨桃 / 小马过河' },
    { id: 'yuwen-2b-06', name: '课文（五）', grade: '二年级下', desc: '古诗二首 / 雷雨 / 要是你在野外迷了路 / 太空生活趣事多' },
    { id: 'yuwen-2b-07', name: '课文（六）', grade: '二年级下', desc: '大象的耳朵 / 蜘蛛开店 / 青蛙卖泥塘 / 小狗的小房子' },
    { id: 'yuwen-2b-08', name: '口语交际', grade: '二年级下', desc: '注意说话的语气 / 推荐一部动画片' },
    { id: 'yuwen-3a-01', name: '课文（一）·学校生活', grade: '三年级上', desc: '大青树下的小学 / 花的学校 / 不懂就要问' },
    { id: 'yuwen-3a-02', name: '课文（二）·金秋时节', grade: '三年级上', desc: '古诗三首 / 铺满金色巴掌的水泥道 / 秋天的雨 / 听听秋的声音' },
    { id: 'yuwen-3a-03', name: '课文（三）·童话世界', grade: '三年级上', desc: '去年的树 / 那一定会很好 / 在牛肚子里旅行 / 一块奶酪' },
    { id: 'yuwen-3a-04', name: '课文（四）·观察发现', grade: '三年级上', desc: '搭船的鸟 / 金色的草地' },
    { id: 'yuwen-3a-05', name: '课文（五）·壮美山河', grade: '三年级上', desc: '富饶的西沙群岛 / 美丽的小兴安岭 / 香港璀璨的明珠' },
    { id: 'yuwen-3a-06', name: '课文（六）·大自然', grade: '三年级上', desc: '大自然的声音 / 父亲树林和鸟 / 带刺的朋友' },
    { id: 'yuwen-3a-07', name: '课文（七）·爱与奉献', grade: '三年级上', desc: '司马光 / 掌声 / 灰雀 / 手术台就是阵地' },
    { id: 'yuwen-3a-08', name: '课文（八）·历史故事', grade: '三年级上', desc: '王戎不取道旁李 / 西门豹 / 故事二则' },
    { id: 'yuwen-3a-09', name: '习作', grade: '三年级上', desc: '猜猜他是谁 / 写日记 / 我来编童话 / 续写故事' },
    { id: 'yuwen-3b-01', name: '课文（一）·春之韵', grade: '三年级下', desc: '古诗三首（绝句/惠崇春江晚景/三衢道中）/ 燕子 / 荷花 / 昆虫备忘录' },
    { id: 'yuwen-3b-02', name: '课文（二）·寓言', grade: '三年级下', desc: '守株待兔 / 陶罐和铁罐 / 鹿角和鹿腿 / 池子与河流' },
    { id: 'yuwen-3b-03', name: '课文（三）·传统文化', grade: '三年级下', desc: '古诗三首 / 纸的发明 / 赵州桥 / 一幅名扬中外的画' },
    { id: 'yuwen-3b-04', name: '课文（四）·观察思考', grade: '三年级下', desc: '花钟 / 蜜蜂 / 小虾' },
    { id: 'yuwen-3b-05', name: '课文（五）·成长故事', grade: '三年级下', desc: '塔克的郊外 / 剃头大师 / 肥皂泡 / 我不能失信' },
    { id: 'yuwen-3b-06', name: '课文（六）·身边的人', grade: '三年级下', desc: '身边那些有特点的人 / 习作人物' },
    { id: 'yuwen-3b-07', name: '课文（七）·奇思妙想', grade: '三年级下', desc: '火烧云 / 宇宙的另一边 / 我变成了一棵树' },
    { id: 'yuwen-3b-08', name: '课文（八）·神话传说', grade: '三年级下', desc: '慢性子裁缝和急性子顾客 / 方帽子店 / 漏 / 枣核' },
    { id: 'yuwen-3b-09', name: '习作', grade: '三年级下', desc: '看图画写作文 / 国宝大熊猫 / 奇妙的想象' },
    { id: 'yuwen-4a-01', name: '课文（一）·自然之美', grade: '四年级上', desc: '观潮 / 走月亮 / 现代诗二首 / 繁星' },
    { id: 'yuwen-4a-02', name: '课文（二）·提问策略', grade: '四年级上', desc: '一个豆荚里的五粒豆 / 蝙蝠和雷达 / 呼风唤雨的世纪 / 蝴蝶的家' },
    { id: 'yuwen-4a-03', name: '课文（三）·古诗', grade: '四年级上', desc: '暮江吟 / 题西林壁 / 雪梅' },
    { id: 'yuwen-4a-04', name: '课文（四）·神话故事', grade: '四年级上', desc: '盘古开天地 / 精卫填海 / 普罗米修斯 / 女娲补天' },
    { id: 'yuwen-4a-05', name: '课文（五）·习作单元', grade: '四年级上', desc: '麻雀 / 爬天都峰 / 习作：生活万花筒' },
    { id: 'yuwen-4a-06', name: '课文（六）·成长', grade: '四年级上', desc: '牛和鹅 / 一只窝囊的大老虎 / 陀螺' },
    { id: 'yuwen-4a-07', name: '课文（七）·爱国人物', grade: '四年级上', desc: '古诗二首 / 为中华之崛起而读书 / 梅兰芳蓄须 / 延安我把你追寻' },
    { id: 'yuwen-4a-08', name: '课文（八）·历史故事', grade: '四年级上', desc: '王戎不取道旁李 / 西门豹治邺 / 故事二则' },
    { id: 'yuwen-4a-09', name: '习作', grade: '四年级上', desc: '推荐一个好地方 / 小小动物园 / 写观察日记' },
    { id: 'yuwen-4b-01', name: '课文（一）·乡村生活', grade: '四年级下', desc: '古诗词三首 / 乡下人家 / 天窗 / 三月桃花水' },
    { id: 'yuwen-4b-02', name: '课文（二）·科技之光', grade: '四年级下', desc: '琥珀 / 飞向蓝天的恐龙 / 纳米技术就在我们身边 / 千年梦圆在今朝' },
    { id: 'yuwen-4b-03', name: '课文（三）·诗歌', grade: '四年级下', desc: '绿 / 海的女儿 / 短诗三首 / 白桦' },
    { id: 'yuwen-4b-04', name: '课文（四）·动物朋友', grade: '四年级下', desc: '猫 / 母鸡 / 白鹅' },
    { id: 'yuwen-4b-05', name: '课文（五）·游记', grade: '四年级下', desc: '海上日出 / 记金华的双龙洞' },
    { id: 'yuwen-4b-06', name: '课文（六）·成长故事', grade: '四年级下', desc: '小英雄雨来 / 我们家的男子汉 / 芦花鞋' },
    { id: 'yuwen-4b-07', name: '课文（七）·中外经典', grade: '四年级下', desc: '古诗三首 / 文言文二则 / 跳水 / 威尼斯的小艇' },
    { id: 'yuwen-4b-08', name: '课文（八）·童话', grade: '四年级下', desc: '宝葫芦的秘密 / 巨人的花园' },
    { id: 'yuwen-4b-09', name: '习作', grade: '四年级下', desc: '我的乐园 / 我的动物朋友 / 游记' },
    { id: 'yuwen-5a-01', name: '课文（一）·花鸟', grade: '五年级上', desc: '白鹭 / 落花生 / 桂花雨 / 珍珠鸟' },
    { id: 'yuwen-5a-02', name: '课文（二）·爱国', grade: '五年级上', desc: '古诗词三首 / 少年中国说 / 圆明园的毁灭 / 无名岛' },
    { id: 'yuwen-5a-03', name: '课文（三）·民间故事', grade: '五年级上', desc: '猎人海力布 / 牛郎织女' },
    { id: 'yuwen-5a-04', name: '课文（四）·说明文', grade: '五年级上', desc: '太阳 / 松鼠' },
    { id: 'yuwen-5a-05', name: '课文（五）·习作单元', grade: '五年级上', desc: '搭石 / 将相和 / 什么比猎豹的速度更快 / 习作：介绍一种事物' },
    { id: 'yuwen-5a-06', name: '课文（六）·父母之爱', grade: '五年级上', desc: '慈母情深 / 父爱之舟 / 精彩极了和糟糕透了' },
    { id: 'yuwen-5a-07', name: '课文（七）·自然', grade: '五年级上', desc: '古诗词三首 / 四季之美 / 鸟的天堂 / 月迹' },
    { id: 'yuwen-5a-08', name: '课文（八）·读书', grade: '五年级上', desc: '古人谈读书 / 忆读书 / 我的长生果' },
    { id: 'yuwen-5b-01', name: '课文（一）·童年', grade: '五年级下', desc: '古诗词三首 / 祖父的园子 / 月是故乡明 / 梅花魂' },
    { id: 'yuwen-5b-02', name: '课文（二）·古典名著', grade: '五年级下', desc: '草船借箭 / 景阳冈 / 猴王出世 / 红楼春趣' },
    { id: 'yuwen-5b-03', name: '综合性学习·汉字', grade: '五年级下', desc: '汉字真有趣 / 我爱你，汉字' },
    { id: 'yuwen-5b-04', name: '课文（四）·责任', grade: '五年级下', desc: '军神 / 青山处处埋忠骨 / 清贫' },
    { id: 'yuwen-5b-05', name: '课文（五）·人物', grade: '五年级下', desc: '人物描写一组 / 刷子李 / 金钱的魔力' },
    { id: 'yuwen-5b-06', name: '课文（六）·思维', grade: '五年级下', desc: '自相矛盾 / 田忌赛马 / 跳水' },
    { id: 'yuwen-5b-07', name: '课文（七）·异域风情', grade: '五年级下', desc: '威尼斯的小艇 / 牧场之国 / 金字塔' },
    { id: 'yuwen-5b-08', name: '课文（八）·幽默', grade: '五年级下', desc: '杨氏之子 / 手指 / 童年的发现' },
    { id: 'yuwen-6a-01', name: '课文（一）·自然', grade: '六年级上', desc: '草原 / 丁香结 / 古诗词三首 / 花之歌' },
    { id: 'yuwen-6a-02', name: '课文（二）·重温革命', grade: '六年级上', desc: '七律·长征 / 狼牙山五壮士 / 开国大典 / 灯光' },
    { id: 'yuwen-6a-03', name: '课文（三）·求知', grade: '六年级上', desc: '竹节人 / 宇宙生命之谜 / 故宫博物院' },
    { id: 'yuwen-6a-04', name: '课文（四）·小说', grade: '六年级上', desc: '桥 / 穷人' },
    { id: 'yuwen-6a-05', name: '课文（五）·习作单元', grade: '六年级上', desc: '夏天里的成长 / 盼 / 习作：围绕中心意思写' },
    { id: 'yuwen-6a-06', name: '课文（六）·环保', grade: '六年级上', desc: '古诗词三首 / 只有一个地球 / 三黑和土地 / 青山不老' },
    { id: 'yuwen-6a-07', name: '课文（七）·艺术', grade: '六年级上', desc: '文言文二则 / 月光曲 / 京剧趣谈' },
    { id: 'yuwen-6a-08', name: '课文（八）·鲁迅', grade: '六年级上', desc: '好的故事 / 我的伯父鲁迅先生 / 有的人' },
    { id: 'yuwen-6b-01', name: '课文（一）·民风民俗', grade: '六年级下', desc: '北京的春节 / 腊八粥 / 古诗三首 / 藏戏' },
    { id: 'yuwen-6b-02', name: '课文（二）·外国名著', grade: '六年级下', desc: '鲁滨逊漂流记 / 骑鹅旅行记 / 汤姆·索亚历险记' },
    { id: 'yuwen-6b-03', name: '课文（三）·真情', grade: '六年级下', desc: '古诗三首 / 那个星期天 / 习作：让真情自然流露' },
    { id: 'yuwen-6b-04', name: '课文（四）·文言', grade: '六年级下', desc: '学弈 / 两小儿辩日' },
    { id: 'yuwen-6b-05', name: '综合性学习', grade: '六年级下', desc: '难忘小学生活 / 成长足迹 / 依依惜别' },
    { id: 'yuwen-6b-06', name: '习作总复习', grade: '六年级下', desc: '小升初作文：审题 / 选材 / 细节' },
  ],
  english: [
    { id: 'e-alpha', name: '英语字母', grade: '启蒙', desc: '26个字母认读 / 大小写 / 顺序' },
    { id: 'e-phonics', name: '自然拼读', grade: '启蒙', desc: '字母发音 / 首字母 / 简单拼读' },
    { id: 'e-words', name: '启蒙单词', grade: '启蒙', desc: '颜色 / 数字 / 动物 / 食物 / 身体' },
    { id: 'e-daily', name: '日常交际', grade: '启蒙', desc: '问候 / 感谢 / 介绍 / 简单句型' },
    { id: 'e-phonics2', name: '拼读规则', grade: '三~四年级', desc: '元音字母发音 / 常见组合 / 重读' },
    { id: 'e-vocab', name: '核心词汇', grade: '三~六年级', desc: '食物职业 / 天气月份 / 形容词副词' },
    { id: 'e-grammar', name: '基础语法', grade: '四~六年级', desc: 'be动词 / 三单 / 过去式 / 现在进行时' },
    { id: 'e-dialog', name: '情景交际', grade: '三~六年级', desc: '问路购物 / 看病 / 打电话 / 发邮件' },
    { id: 'e-read', name: '短文阅读', grade: '五~六年级', desc: '读短文选答案 / 判断正误' },
    // ---- 人教PEP英语 3-6 年级上下册单元目录 ----
    { id: 'eng-3a-01', name: 'Unit 1 Hello!', grade: '三年级上', desc: '问候 / 文具 pen pencil ruler' },
    { id: 'eng-3a-02', name: 'Unit 2 Colours', grade: '三年级上', desc: '颜色 red yellow blue green / I see…' },
    { id: 'eng-3a-03', name: 'Unit 3 Look at me!', grade: '三年级上', desc: '身体部位 face ear eye nose mouth' },
    { id: 'eng-3a-04', name: 'Unit 4 We love animals', grade: '三年级上', desc: '动物 cat dog pig duck / 拟声词' },
    { id: 'eng-3a-05', name: "Unit 5 Let's eat!", grade: '三年级上', desc: '食物 bread egg milk rice / Have some…' },
    { id: 'eng-3a-06', name: 'Unit 6 Happy birthday!', grade: '三年级上', desc: '数字 1-10 / 年龄 How old are you?' },
    { id: 'eng-3b-01', name: 'Unit 1 Welcome back to school!', grade: '三年级下', desc: '新同学新老师 / boy or girl' },
    { id: 'eng-3b-02', name: 'Unit 2 My family', grade: '三年级下', desc: '家庭成员 / This is my…' },
    { id: 'eng-3b-03', name: 'Unit 3 At the zoo', grade: '三年级下', desc: '动物 big small long short / Look at…' },
    { id: 'eng-3b-04', name: 'Unit 4 Where is my car?', grade: '三年级下', desc: '方位 in on under / 玩具 car boat' },
    { id: 'eng-3b-05', name: 'Unit 5 Do you like pears?', grade: '三年级下', desc: '水果 apple pear orange / Do you like…?' },
    { id: 'eng-3b-06', name: 'Unit 6 How many?', grade: '三年级下', desc: '数字 11-20 / How many…?' },
    { id: 'eng-4a-01', name: 'Unit 1 My classroom', grade: '四年级上', desc: '教室 window door light / Where is…?' },
    { id: 'eng-4a-02', name: 'Unit 2 My schoolbag', grade: '四年级上', desc: '文具 maths book storybook / What colour?' },
    { id: 'eng-4a-03', name: 'Unit 3 My friends', grade: '四年级上', desc: '外貌 tall strong friendly / He has…' },
    { id: 'eng-4a-04', name: 'Unit 4 My home', grade: '四年级上', desc: '房间 study kitchen bedroom / Is this…?' },
    { id: 'eng-4a-05', name: 'Unit 5 What would you like?', grade: '四年级上', desc: '食物 noodles soup / I’d like…' },
    { id: 'eng-4a-06', name: 'Unit 6 Meet my family!', grade: '四年级上', desc: '职业 doctor farmer driver / How many people?' },
    { id: 'eng-4b-01', name: 'Unit 1 My school', grade: '四年级下', desc: '学校场所 playground library / 时间 first second' },
    { id: 'eng-4b-02', name: 'Unit 2 What time is it?', grade: '四年级下', desc: '时间 3点 / 课程 music PE / It’s time for…' },
    { id: 'eng-4b-03', name: 'Unit 3 Weather', grade: '四年级下', desc: '天气 sunny rainy windy / How about…?' },
    { id: 'eng-4b-04', name: 'Unit 4 At the farm', grade: '四年级下', desc: '农场动物 sheep hen / 数量 these those' },
    { id: 'eng-4b-05', name: 'Unit 5 My clothes', grade: '四年级下', desc: '服装 jacket dress / 试穿 Can I try…?' },
    { id: 'eng-4b-06', name: 'Unit 6 Shopping', grade: '四年级下', desc: '购物 price / How much? / 大小码' },
    { id: 'eng-5a-01', name: "Unit 1 What's he like?", grade: '五年级上', desc: '性格 old young funny / 第三人称单数' },
    { id: 'eng-5a-02', name: 'Unit 2 My week', grade: '五年级上', desc: '星期 / 课程 often wash' },
    { id: 'eng-5a-03', name: 'Unit 3 What would you like?', grade: '五年级上', desc: '三餐 food drink / What’s your favourite?' },
    { id: 'eng-5a-04', name: 'Unit 4 What can you do?', grade: '五年级上', desc: '能力 dance sing swim / 情态动词can' },
    { id: 'eng-5a-05', name: 'Unit 5 There is a big bed', grade: '五年级上', desc: 'there be 句型 / 房间摆设' },
    { id: 'eng-5a-06', name: 'Unit 6 In a nature park', grade: '五年级上', desc: '自然 river lake forest / Is there…?' },
    { id: 'eng-5b-01', name: 'Unit 1 My day', grade: '五年级下', desc: '作息 when do you…? / usually' },
    { id: 'eng-5b-02', name: 'Unit 2 My favourite season', grade: '五年级下', desc: '季节 spring summer / 天气活动 swim skate' },
    { id: 'eng-5b-03', name: 'Unit 3 My school calendar', grade: '五年级下', desc: '月份 January-December / 节日 Easter' },
    { id: 'eng-5b-04', name: 'Unit 4 When is the art show?', grade: '五年级下', desc: '日期 / 生日 When is your birthday?' },
    { id: 'eng-5b-05', name: 'Unit 5 Whose dog is it?', grade: '五年级下', desc: '物主代词 mine yours / 爬行 jumping' },
    { id: 'eng-5b-06', name: 'Unit 6 Work quietly!', grade: '五年级下', desc: '现在进行时 He is listening / 课堂用语' },
    { id: 'eng-6a-01', name: 'Unit 1 How can I get there?', grade: '六年级上', desc: '问路 turn left right / near far' },
    { id: 'eng-6a-02', name: 'Unit 2 Ways to go to school', grade: '六年级上', desc: '交通 on foot by bus / How do you…?' },
    { id: 'eng-6a-03', name: 'Unit 3 My weekend plan', grade: '六年级上', desc: '计划 visit see a film / be going to' },
    { id: 'eng-6a-04', name: 'Unit 4 I have a pen pal', grade: '六年级上', desc: '爱好 hobby read stories / like doing' },
    { id: 'eng-6a-05', name: 'Unit 5 What does he do?', grade: '六年级上', desc: '职业 worker engineer / Where does he work?' },
    { id: 'eng-6a-06', name: 'Unit 6 How do you feel?', grade: '六年级上', desc: '情绪 happy sad worried / should 建议' },
    { id: 'eng-6b-01', name: 'Unit 1 How tall are you?', grade: '六年级下', desc: '比较级 taller longer older / 测量' },
    { id: 'eng-6b-02', name: 'Unit 2 Last weekend', grade: '六年级下', desc: '一般过去时 washed watched / 昨天活动' },
    { id: 'eng-6b-03', name: 'Unit 3 Where did you go?', grade: '六年级下', desc: '过去时 went ate / 假期 mule beach' },
    { id: 'eng-6b-04', name: 'Unit 4 Then and now', grade: '六年级下', desc: '过去与现在对比 / was were' },
  ],
  science: [
    { id: 's-plant', name: '植物朋友', grade: '一二年级', desc: '种子发芽 / 植物部位 / 生长需要' },
    { id: 's-animal', name: '动物世界', grade: '一二年级', desc: '习性 / 呼吸 / 运动方式' },
    { id: 's-body', name: '身体与感官', grade: '一年级', desc: '五官 / 感觉 / 保护身体' },
    { id: 's-matter', name: '水空气材料', grade: '一二年级', desc: '水的变化 / 空气 / 物体特征' },
    { id: 's-light', name: '光与影', grade: '二年级', desc: '影子 / 光源 / 昼夜' },
    { id: 's-weather', name: '天气与四季', grade: '一二年级', desc: '天气现象 / 四季特点 / 观察记录' },
    { id: 's-motion', name: '运动与力', grade: '三~四年级', desc: '运动快慢 / 摩擦力 / 弹力浮力' },
    { id: 's-electric', name: '电', grade: '四年级', desc: '简单电路 / 导体绝缘体 / 安全用电' },
    { id: 's-solar', name: '地球与宇宙', grade: '五~六年级', desc: '昼夜月相 / 太阳系 / 星座' },
    { id: 's-bio', name: '生物与环境', grade: '五~六年级', desc: '食物链 / 生物适应 / 生态保护' },
    { id: 's-tech', name: '材料与工程', grade: '三~六年级', desc: '材料性质 / 工具 / 设计建造' },
    // ---- 小学科学 1-6 年级上下册单元目录（教科版对齐，跳过总复习）----
    { id: 'sci-1a-01', name: '我们知道的植物', grade: '一年级上', desc: '认识植物 / 根茎叶' },
    { id: 'sci-1a-02', name: '我们知道的动物', grade: '一年级上', desc: '认识动物 / 动物特征' },
    { id: 'sci-1a-03', name: '我们周围的物体', grade: '一年级上', desc: '物体的形状 / 轻重' },
    { id: 'sci-1a-04', name: '水和空气', grade: '一年级上', desc: '水的特点 / 空气的存在' },
    { id: 'sci-1b-01', name: '物体的特征', grade: '一年级下', desc: '给物体分类 / 共同特征' },
    { id: 'sci-1b-02', name: '动物', grade: '一年级下', desc: '动物的运动 / 食物' },
    { id: 'sci-1b-03', name: '植物', grade: '一年级下', desc: '植物的生长 / 叶和花' },
    { id: 'sci-1b-04', name: '水', grade: '一年级下', desc: '水的多少 / 沉浮初探' },
    { id: 'sci-2a-01', name: '地球家园', grade: '二年级上', desc: '陆地海洋 / 地球家园中有什么' },
    { id: 'sci-2a-02', name: '土壤', grade: '二年级上', desc: '土壤里的动植物 / 爱护土壤' },
    { id: 'sci-2a-03', name: '水', grade: '二年级上', desc: '水的三态初识 / 节约用水' },
    { id: 'sci-2b-01', name: '我们自己', grade: '二年级下', desc: '身体 / 生长变化' },
    { id: 'sci-2b-02', name: '植物', grade: '二年级下', desc: '种子发芽 / 植物需要' },
    { id: 'sci-2b-03', name: '天气', grade: '二年级下', desc: '天气观察 / 天气与生活' },
    { id: 'sci-2b-04', name: '水', grade: '二年级下', desc: '水的流动 / 水的用途' },
    { id: 'sci-3a-01', name: '植物', grade: '三年级上', desc: '根茎叶 / 花果实种子' },
    { id: 'sci-3a-02', name: '动物', grade: '三年级上', desc: '动物类型 / 迁徙冬眠' },
    { id: 'sci-3a-03', name: '我们周围的材料', grade: '三年级上', desc: '材料性质 / 纸和砖瓦' },
    { id: 'sci-3a-04', name: '水和空气', grade: '三年级上', desc: '水的形态 / 空气占据空间' },
    { id: 'sci-3b-01', name: '植物的生长变化', grade: '三年级下', desc: '播种发芽 / 开花结果' },
    { id: 'sci-3b-02', name: '动物的生命周期', grade: '三年级下', desc: '蚕/鸡的一生 / 变态发育' },
    { id: 'sci-3b-03', name: '温度与水的变化', grade: '三年级下', desc: '温度计 / 水结冰融化蒸发' },
    { id: 'sci-3b-04', name: '磁铁', grade: '三年级下', desc: '磁极 / 磁铁玩具' },
    { id: 'sci-4a-01', name: '声音', grade: '四年级上', desc: '声音产生传播 / 音量音调' },
    { id: 'sci-4a-02', name: '呼吸与消化', grade: '四年级上', desc: '肺活量 / 食物的旅行' },
    { id: 'sci-4a-03', name: '运动和力', grade: '四年级上', desc: '运动快慢 / 摩擦力 / 弹力' },
    { id: 'sci-4b-01', name: '电', grade: '四年级下', desc: '简单电路 / 导体绝缘体 / 安全用电' },
    { id: 'sci-4b-02', name: '新的生命', grade: '四年级下', desc: '花的构造 / 繁殖' },
    { id: 'sci-4b-03', name: '食物', grade: '四年级下', desc: '营养 / 食物变质' },
    { id: 'sci-4b-04', name: '岩石和矿物', grade: '四年级下', desc: '岩石组成 / 矿物观察' },
    { id: 'sci-5a-01', name: '光', grade: '五年级上', desc: '光的传播 / 反射 / 透镜' },
    { id: 'sci-5a-02', name: '地球表面的变化', grade: '五年级上', desc: '风化侵蚀 / 火山地震' },
    { id: 'sci-5a-03', name: '计量时间', grade: '五年级上', desc: '钟摆 / 日晷 / 计时工具' },
    { id: 'sci-5a-04', name: '健康生活', grade: '五年级上', desc: '心脏肺 / 营养运动' },
    { id: 'sci-5b-01', name: '沉和浮', grade: '五年级下', desc: '浮力 / 改变沉浮' },
    { id: 'sci-5b-02', name: '热', grade: '五年级下', desc: '热传递 / 热胀冷缩 / 保温' },
    { id: 'sci-5b-03', name: '时间的测量', grade: '五年级下', desc: '摆的快慢 / 机械钟表' },
    { id: 'sci-5b-04', name: '地球的运动', grade: '五年级下', desc: '昼夜交替 / 月相 / 四季' },
    { id: 'sci-6a-01', name: '工具和机械', grade: '六年级上', desc: '杠杆 / 滑轮 / 斜面' },
    { id: 'sci-6a-02', name: '形状与结构', grade: '六年级上', desc: '拱形 / 框架 / 桥' },
    { id: 'sci-6a-03', name: '能量', grade: '六年级上', desc: '能量形式 / 转化 / 节约能源' },
    { id: 'sci-6a-04', name: '生物的多样性', grade: '六年级上', desc: '物种 / 食物链 / 保护' },
    { id: 'sci-6b-01', name: '放大镜', grade: '六年级下', desc: '放大镜构造 / 显微镜' },
    { id: 'sci-6b-02', name: '环境和我们', grade: '六年级下', desc: '垃圾 / 水污染 / 环保行动' },
    { id: 'sci-6b-03', name: '宇宙', grade: '六年级下', desc: '太阳系 / 星座 / 探索宇宙' },
    { id: 'sci-6b-04', name: '物质的变化', grade: '六年级下', desc: '物理变化 / 化学变化' },
  ],
  life: [
    { id: 'l-safety', name: '安全自护', grade: '一二年级', desc: '交通 / 校园 / 居家 / 求助电话' },
    { id: 'l-health', name: '健康习惯', grade: '一二年级', desc: '卫生 / 作息 / 运动 / 护眼' },
    { id: 'l-manners', name: '交往与规则', grade: '一二年级', desc: '礼貌用语 / 课堂规则 / 分享合作' },
    { id: 'l-love', name: '爱家爱国环保', grade: '一二年级', desc: '国旗 / 节日 / 节约 / 环保' },
    { id: 'l-rule', name: '法律启蒙', grade: '三~四年级', desc: '规则意识 / 宪法 / 未成年人保护' },
    { id: 'l-soc', name: '社会交往', grade: '三~五年级', desc: '合作诚信 / 网络安全 / 集体生活' },
    { id: 'l-china', name: '传统文化与国情', grade: '五~六年级', desc: '传统节日习俗 / 成语典故 / 国家成就' },
    { id: 'l-eco', name: '资源与环保', grade: '三~六年级', desc: '垃圾分类 / 节水节电 / 低碳生活' },
    // ---- 道德与法治 1-6 年级上下册单元目录（部编版对齐）----
    { id: 'ddf-1a-01', name: '开心上学', grade: '一年级上', desc: '上学真快乐 / 认识新朋友' },
    { id: 'ddf-1a-02', name: '我们的校园', grade: '一年级上', desc: '校园探秘 / 爱护校园' },
    { id: 'ddf-1a-03', name: '安全出行', grade: '一年级上', desc: '上学路上 / 交通安全' },
    { id: 'ddf-1a-04', name: '温暖的家', grade: '一年级上', desc: '我爱我家 / 家人的爱' },
    { id: 'ddf-1b-01', name: '我的好习惯', grade: '一年级下', desc: '卫生 / 作息 / 学习习惯' },
    { id: 'ddf-1b-02', name: '我和大自然', grade: '一年级下', desc: '亲近自然 / 爱护花草' },
    { id: 'ddf-1b-03', name: '我爱我家', grade: '一年级下', desc: '家人分工 / 感恩' },
    { id: 'ddf-1b-04', name: '我们在一起', grade: '一年级下', desc: '分享 / 合作' },
    { id: 'ddf-2a-01', name: '我们的节日', grade: '二年级上', desc: '国庆 / 中秋 / 传统节日' },
    { id: 'ddf-2a-02', name: '公共场所', grade: '二年级上', desc: '遵守秩序 / 爱护公物' },
    { id: 'ddf-2a-03', name: '饮食健康', grade: '二年级上', desc: '好好吃饭 / 食品安全' },
    { id: 'ddf-2a-04', name: '安全', grade: '二年级上', desc: '校园安全 / 居家安全' },
    { id: 'ddf-2b-01', name: '节约用纸', grade: '二年级下', desc: '纸的由来 / 节约' },
    { id: 'ddf-2b-02', name: '健康游戏', grade: '二年级下', desc: '有益游戏 / 不沉迷' },
    { id: 'ddf-2b-03', name: '环保', grade: '二年级下', desc: '垃圾分类 / 绿色生活' },
    { id: 'ddf-2b-04', name: '热爱劳动', grade: '二年级下', desc: '自己的事自己做 / 尊重劳动' },
    { id: 'ddf-3a-01', name: '快乐学习', grade: '三年级上', desc: '学习方法 / 时间管理' },
    { id: 'ddf-3a-02', name: '我们的学校', grade: '三年级上', desc: '学校变化 / 为学校骄傲' },
    { id: 'ddf-3a-03', name: '安全护我成长', grade: '三年级上', desc: '平安出行 / 消防 / 防溺水' },
    { id: 'ddf-3a-04', name: '家是最温暖的地方', grade: '三年级上', desc: '家庭责任 / 沟通理解' },
    { id: 'ddf-3b-01', name: '同伴交往', grade: '三年级下', desc: '交朋友 / 尊重差异' },
    { id: 'ddf-3b-02', name: '家乡', grade: '三年级下', desc: '家乡物产 / 热爱家乡' },
    { id: 'ddf-3b-03', name: '公共生活', grade: '三年级下', desc: '公共规则 / 爱护公物' },
    { id: 'ddf-3b-04', name: '爱护生命', grade: '三年级下', desc: '生命可贵 / 安全自护' },
    { id: 'ddf-4a-01', name: '与班级共成长', grade: '四年级上', desc: '班规 / 集体荣誉' },
    { id: 'ddf-4a-02', name: '为父母分担', grade: '四年级上', desc: '孝敬 / 家务劳动' },
    { id: 'ddf-4a-03', name: '信息万花筒', grade: '四年级上', desc: '网络安全 / 辨别信息' },
    { id: 'ddf-4a-04', name: '让生活多一些绿色', grade: '四年级上', desc: '环保行动 / 低碳' },
    { id: 'ddf-4b-01', name: '世界文化', grade: '四年级下', desc: '各国节日 / 文化差异' },
    { id: 'ddf-4b-02', name: '诚信', grade: '四年级下', desc: '诚实守信 / 承诺' },
    { id: 'ddf-4b-03', name: '美好生活', grade: '四年级下', desc: '科技生活 / 消费' },
    { id: 'ddf-4b-04', name: '绿色消费', grade: '四年级下', desc: '理性消费 / 维权' },
    { id: 'ddf-5a-01', name: '成长新问题', grade: '五年级上', desc: '自主独立 / 面对挫折' },
    { id: 'ddf-5a-02', name: '班级主人', grade: '五年级上', desc: '参与管理 / 责任' },
    { id: 'ddf-5a-03', name: '国土家园', grade: '五年级上', desc: '疆域 / 资源' },
    { id: 'ddf-5a-04', name: '灿烂文化', grade: '五年级上', desc: '传统文化 / 文明成就' },
    { id: 'ddf-5b-01', name: '国家形象', grade: '五年级下', desc: '国家尊严 / 礼仪' },
    { id: 'ddf-5b-02', name: '富强创新', grade: '五年级下', desc: '科技成就 / 创新' },
    { id: 'ddf-5b-03', name: '民族团结', grade: '五年级下', desc: '民族政策 / 团结' },
    { id: 'ddf-5b-04', name: '中国梦', grade: '五年级下', desc: '梦想 / 奋斗' },
    { id: 'ddf-6a-01', name: '健康成长', grade: '六年级上', desc: '情绪管理 / 心理健康' },
    { id: 'ddf-6a-02', name: '我们是公民', grade: '六年级上', desc: '公民身份 / 权利义务' },
    { id: 'ddf-6a-03', name: '国家机构', grade: '六年级上', desc: '人大 / 政府 / 法院' },
    { id: 'ddf-6a-04', name: '法律保护', grade: '六年级上', desc: '宪法 / 未成年人保护法' },
    { id: 'ddf-6b-01', name: '完善自我', grade: '六年级下', desc: '认识自己 / 规划成长' },
    { id: 'ddf-6b-02', name: '爱护地球', grade: '六年级下', desc: '环境危机 / 共同责任' },
    { id: 'ddf-6b-03', name: '多样文明', grade: '六年级下', desc: '世界文化 / 尊重差异' },
    { id: 'ddf-6b-04', name: '让世界更美好', grade: '六年级下', desc: '和平 / 公益' },
  ],
  geography: [
    { id: 'g-direction', name: '方向与位置', grade: '启蒙', desc: '前后左右 / 东南西北 / 指南针' },
    { id: 'g-earth', name: '地球家园', grade: '启蒙', desc: '地球 / 地图 / 家乡 / 中国' },
    { id: 'g-sky', name: '日月星空', grade: '启蒙', desc: '太阳月亮 / 昼夜 / 星空' },
    { id: 'g-map', name: '地图与地形', grade: '四~六年级', desc: '方向比例尺 / 中国地形 / 长江黄河' },
    { id: 'g-climate', name: '气候与灾害', grade: '四~六年级', desc: '气候类型 / 台风地震 / 防灾' },
    { id: 'g-china', name: '中国地理', grade: '三~六年级', desc: '省会 / 名山大川 / 名胜' },
    { id: 'g-world', name: '世界地理', grade: '五~六年级', desc: '七大洲四大洋 / 主要国家' },
    // ---- 地理常识 12 讲（小学阶段循序渐进）----
    { id: 'geo-01', name: '方向与位置', grade: '一~二年级', desc: '前后左右 / 东南西北 / 看太阳辨方向' },
    { id: 'geo-02', name: '指南针与地图符号', grade: '二~三年级', desc: '指南针使用 / 图例 / 简单平面图' },
    { id: 'geo-03', name: '地球与地球仪', grade: '三年级', desc: '地球形状 / 纬线经线 / 东西半球' },
    { id: 'geo-04', name: '地图与比例尺', grade: '四年级', desc: '方向 / 比例尺换算 / 等高线初识' },
    { id: 'geo-05', name: '中国的疆域与省份', grade: '四~五年级', desc: '版图 / 34个省级行政区 / 首都' },
    { id: 'geo-06', name: '地形地貌', grade: '五年级', desc: '高原平原 / 盆地丘陵 / 主要山脉' },
    { id: 'geo-07', name: '长江与黄河', grade: '五年级', desc: '发源地 / 流经省份 / 保护母亲河' },
    { id: 'geo-08', name: '气候与天气', grade: '四~五年级', desc: '气温降水 / 季风气候 / 天气预报' },
    { id: 'geo-09', name: '自然灾害与防灾', grade: '五~六年级', desc: '地震台风洪水 / 逃生自救' },
    { id: 'geo-10', name: '省会与名胜', grade: '三~六年级', desc: '各省省会 / 长城故宫 / 名山大川' },
    { id: 'geo-11', name: '七大洲四大洋', grade: '六年级', desc: '洲洋名称位置 / 最大最小' },
    { id: 'geo-12', name: '世界主要国家', grade: '六年级', desc: '人口大国 / 邻国 / 首都' },
  ],
};

export const knowledgeName = (subjectId, knowledgeId) =>
  KNOWLEDGE[subjectId]?.find((k) => k.id === knowledgeId)?.name || '综合';

// 单元年级标签（如'三年级上'）；未知返回'综合'
export const unitGrade = (subjectId, knowledgeId) =>
  KNOWLEDGE[subjectId]?.find((k) => k.id === knowledgeId)?.grade || '综合';

// 题型尽量贴近真实考试:看图选 / 选择 / 判断 / 填空 / 排序 / 应用 / 交际
export const BANKS = {
  math: [
    { k: 'm-count', t: '数的组成', p: '10 个一是几个十？是几？', v: '🧮', a: '1个十，是10', o: ['1个十，是10', '10个十，是100', '1个一，是1', '2个十，是20'], e: '10个一合起来就是1个十，也就是10。' },
    { k: 'm-count', t: '数的读写', p: '“四十五”写成数字是？', v: '✏️', a: '45', o: ['45', '54', '405', '450'], e: '四十五就是4个十加5个一，写作45。' },
    { k: 'm-add20', t: '进位加法', p: '算一算：9 + 5 = ?', v: '🍎 9 + 5', a: 14, o: [14, 13, 15, 12], e: '用凑十法：把5分成1和4，9+1=10，10+4=14。' },
    { k: 'm-add20', t: '退位减法', p: '算一算：13 − 4 = ?', v: '🍪 13 − 4', a: 9, o: [9, 8, 10, 11], e: '13减4：13−3=10，10−1=9。' },
    { k: 'm-add100', t: '整十加减', p: '算一算：34 + 20 = ?', v: '🧮 34 + 20', a: 54, o: [54, 53, 64, 44], e: '整十数相加只看十位：3个十加2个十是5个十，34+20=54。' },
    { k: 'm-add100', t: '两位数减法', p: '算一算：56 − 30 = ?', v: '🧮 56 − 30', a: 26, o: [26, 25, 36, 16], e: '5个十减3个十剩2个十，56−30=26。' },
    { k: 'm-mult', t: '乘法口诀', p: '3 × 4 = ? 用哪句口诀？', v: '🐟 3 × 4', a: 12, o: [12, 7, 9, 16], e: '口诀“三四十二”，3×4=12。' },
    { k: 'm-mult', t: '乘法含义', p: '4 个 5 相加，写成乘法是？', v: '🍓🍓🍓🍓', a: '4×5', o: ['4×5', '4+5', '5−4', '4÷5'], e: '4个5相加就是4×5，表示4个5合起来。' },
    { k: 'm-div', t: '平均分', p: '12 颗糖平均分给 3 个小朋友，每人几颗？', v: '🍬 ÷ 3', a: 4, o: [4, 3, 6, 9], e: '12÷3=4，想口诀“三四十二”，每人4颗。' },
    { k: 'm-length', t: '单位换算', p: '1 米 = ( ) 厘米', v: '📏', a: 100, o: [100, 10, 1000, 1], e: '1米等于100厘米，记住：1米=100厘米。' },
    { k: 'm-length', t: '测量估计', p: '一支新铅笔大约有多长？', v: '✏️', a: '15厘米', o: ['15厘米', '15米', '1厘米', '50厘米'], e: '铅笔大约15厘米长，用厘米不用米。' },
    { k: 'm-angle', t: '角的认识', p: '三角尺上最大的角是什么角？', v: '📐', a: '直角', o: ['直角', '锐角', '钝角', '圆角'], e: '三角尺上最大的角是直角，直直的像桌角。' },
    { k: 'm-time', t: '认识钟表', p: '时针指着 3，分针指着 12，是几时？', v: '🕒', a: '3时', o: ['3时', '12时', '3时半', '12时半'], e: '分针指12、时针指几就是几时，这是3时。' },
    { k: 'm-money', t: '人民币换算', p: '1 元 = ( ) 角', v: '💴', a: 10, o: [10, 100, 5, 1], e: '1元=10角，10个1角就是1元。' },
    { k: 'm-shape', t: '立体图形', p: '足球是什么形状？', v: '⚽', a: '球', o: ['球', '正方体', '圆柱', '长方体'], e: '足球圆滚滚会滚动，就是球。' },
    { k: 'm-pattern', t: '找规律', p: '找规律：2, 4, 6, □，方框里是？', v: '🔢 2 4 6 □', a: 8, o: [8, 7, 10, 12], e: '每次多2：2、4、6，下一个是8。' },
    { k: 'm-word', t: '应用题', p: '小明有 10 颗糖，吃了 3 颗，又买了 5 颗，现在有几颗？', v: '🍬', a: 12, o: [12, 10, 8, 15], e: '10−3=7，7+5=12，现在有12颗。' },
    { k: 'math-3a-08', t: '分数含义', p: '把一个苹果平均分成 4 份，每份是这个苹果的？', v: '🍎 ÷ 4', a: '四分之一', o: ['四分之一', '四分之四', '一份', '一半'], e: '平均分成4份，每份就是四分之一，写作 1/4。' },
    { k: 'math-3a-08', t: '分数比较', p: '比较大小：1/3 ○ 1/5，应该填？', v: '1/3 ○ 1/5', a: '＞', o: ['＞', '＜', '=', '＋'], e: '分子都是1，分母小的分数反而大：1/3 ＞ 1/5。' },
    { k: 'math-3a-08', t: '同分母加法', p: '算一算：2/7 + 3/7 = ?', v: '2/7 + 3/7', a: '5/7', o: ['5/7', '5/14', '6/7', '1'], e: '同分母相加，分母不变，分子相加：2+3=5，是5/7。' },
    { k: 'math-5b-04', t: '真假分数', p: '下面哪个是假分数？', v: '🔢', a: '7/5', o: ['7/5', '3/8', '1/2', '2/9'], e: '分子大于或等于分母的是假分数：7/5。' },
    { k: 'math-5b-04', t: '分数基本性质', p: '3/4 的分子分母同时乘 2，得到？', v: '3/4 × 2', a: '6/8', o: ['6/8', '5/6', '3/8', '6/4'], e: '分数的分子分母同时乘相同的数，分数大小不变：3/4=6/8。' },
    { k: 'math-5b-06', t: '异分母加法', p: '算一算：1/2 + 1/3 = ?', v: '1/2 + 1/3', a: '5/6', o: ['5/6', '2/5', '1/6', '2/6'], e: '先通分：1/2=3/6，1/3=2/6，3/6+2/6=5/6。' },
    { k: 'math-3b-07', t: '小数读写', p: '“零点八”写成小数是？', v: '✏️', a: '0.8', o: ['0.8', '0.08', '8.0', '80'], e: '零点八就是0.8，小数点后面一位是十分位。' },
    { k: 'math-3b-07', t: '小数比较', p: '比较大小：0.6 ○ 0.59，应该填？', v: '0.6 ○ 0.59', a: '＞', o: ['＞', '＜', '=', '＋'], e: '0.6=0.60，0.60 ＞ 0.59，所以填＞。' },
    { k: 'math-4b-06', t: '小数加减', p: '算一算：5.3 + 2.7 = ?', v: '5.3 + 2.7', a: '8', o: ['8', '7', '8.10', '7.10'], e: '小数点对齐再算：5.3+2.7=8.0，也就是8。' },
    { k: 'math-4b-03', t: '加法简算', p: '用简便方法算：27 + 36 + 73 = ?', v: '🧮', a: 136, o: [136, 126, 146, 130], e: '用加法结合律：27+73=100，100+36=136。' },
    { k: 'math-4b-03', t: '乘法分配律', p: '算一算：25 × (4 + 8) = ?', v: '25 × (4 + 8)', a: 300, o: [300, 108, 200, 132], e: '乘法分配律：25×4+25×8=100+200=300。' },
    { k: 'math-4b-03', t: '常见简算', p: '125 × 8 × 4 的简便结果是？', v: '🧮', a: 4000, o: [4000, 1000, 400, 425], e: '125×8=1000，1000×4=4000，记住125×8=1000。' },
    { k: 'math-3b-06', t: '年月日', p: '一年有几个月？大月有几天？', v: '📅', a: '12个月，大月31天', o: ['12个月，大月31天', '10个月，大月30天', '12个月，大月30天', '11个月，大月31天'], e: '一年12个月，1、3、5、7、8、10、12月是大月，每月31天。' },
    { k: 'math-3b-06', t: '平年闰年', p: '2024 年是平年还是闰年？2月有几天？', v: '📅 2024', a: '闰年，29天', o: ['闰年，29天', '平年，28天', '闰年，28天', '平年，29天'], e: '2024能被4整除，是闰年，2月有29天。口诀：四年一闰。' },
    { k: 'math-3b-05', t: '长方形面积', p: '长 8 厘米、宽 5 厘米的长方形，面积是？', v: '▭ 8×5', a: '40平方厘米', o: ['40平方厘米', '26平方厘米', '13平方厘米', '40厘米'], e: '长方形面积=长×宽=8×5=40平方厘米。注意单位是平方厘米。' },
    { k: 'math-5a-06', t: '三角形面积', p: '底 10、高 6 的三角形，面积是？', v: '🔺', a: 30, o: [30, 60, 16, 36], e: '三角形面积=底×高÷2=10×6÷2=30，别忘了除以2。' },
    { k: 'math-5a-06', t: '梯形面积', p: '上底 4、下底 8、高 5 的梯形，面积是？', v: '⬠', a: 30, o: [30, 60, 34, 20], e: '梯形面积=(上底+下底)×高÷2=(4+8)×5÷2=30。' },
    { k: 'math-6a-05', t: '圆的周长', p: '直径是 10 厘米的圆，周长大约是？(π取3.14)', v: '⭕ d=10', a: '31.4厘米', o: ['31.4厘米', '314厘米', '15.7厘米', '31.4平方厘米'], e: '圆周长=π×直径=3.14×10=31.4厘米。' },
    { k: 'math-6a-05', t: '圆的面积', p: '半径是 3 厘米的圆，面积大约是？(π取3.14)', v: '⭕ r=3', a: '28.26平方厘米', o: ['28.26平方厘米', '18.84平方厘米', '9.42平方厘米', '28.26厘米'], e: '圆面积=πr²=3.14×3×3=28.26平方厘米。' },
    { k: 'math-5a-05', t: '解方程', p: '解方程：x + 7 = 15，x = ?', v: 'x + 7 = 15', a: 8, o: [8, 22, 7, 9], e: '等式两边同时减7：x=15−7=8。记得写“解：”。' },
    { k: 'math-5a-05', t: '方程应用', p: '小红买了 3 支同样的笔，共花 12 元。设每支 x 元，列方程是？', v: '✏️×3=12', a: '3x=12', o: ['3x=12', 'x+3=12', 'x−3=12', '12−x=3'], e: '3支共12元：3x=12，解得x=4，每支4元。' },
    { k: 'math-5b-02', t: '质数合数', p: '下面哪个数是质数？', v: '🔢', a: 13, o: [13, 15, 21, 27], e: '质数只有1和它本身两个因数：13是质数，15、21、27都能被3整除。' },
    { k: 'math-5b-02', t: '2、5倍数特征', p: '既是 2 的倍数、又是 5 的倍数的数，个位一定是？', v: '🔢', a: 0, o: [0, 5, 2, 8], e: '2的倍数个位是偶数，5的倍数个位是0或5，同时满足只能是个位0。' },
    { k: 'math-6a-04', t: '比的化简', p: '化简比：12 : 18 = ?', v: '12 : 18', a: '2:3', o: ['2:3', '3:2', '4:6', '6:9'], e: '比的前后项同时除以6：12:18=2:3，要化到最简。' },
    { k: 'math-6a-04', t: '按比分配', p: '糖果按 2:3 分给小明和小红，共 30 颗，小明得几颗？', v: '🍬 2:3', a: 12, o: [12, 18, 10, 15], e: '总份数2+3=5，每份30÷5=6颗，小明2份得12颗。' },
    { k: 'math-6a-06', t: '百分数互化', p: '0.75 化成百分数是？', v: '0.75 → %', a: '75%', o: ['75%', '7.5%', '750%', '0.75%'], e: '小数化百分数，小数点向右移两位：0.75=75%。' },
    { k: 'math-6b-02', t: '折扣问题', p: '原价 100 元的书包打八折，现价是？', v: '🎒 八折', a: '80元', o: ['80元', '20元', '8元', '92元'], e: '八折就是按原价的80%卖：100×80%=80元。' },
    { k: 'math-6b-03', t: '圆柱体积', p: '底面积 20 平方厘米、高 5 厘米的圆柱，体积是？', v: '🛢️', a: '100立方厘米', o: ['100立方厘米', '50立方厘米', '25立方厘米', '100平方厘米'], e: '圆柱体积=底面积×高=20×5=100立方厘米。' },
    { k: 'math-6b-04', t: '比例尺', p: '比例尺 1:1000，图上 3 厘米表示实际几米？', v: '🗺️ 1:1000', a: '30米', o: ['30米', '300米', '3米', '3000米'], e: '实际距离=3×1000=3000厘米=30米，注意换算单位。' },
    { k: 'math-6b-04', t: '正反比例', p: '速度一定，路程和时间成什么比例？', v: '🚗', a: '正比例', o: ['正比例', '反比例', '不成比例', '无法判断'], e: '路程÷时间=速度（一定），比值一定，成正比例。' },
    { k: 'math-4b-08', t: '平均数', p: '小明三次得分 90、95、85，平均分是？', v: '📊', a: 90, o: [90, 95, 85, 270], e: '平均数=总数÷份数=(90+95+85)÷3=270÷3=90。' },
    { k: 'math-5b-07', t: '折线统计图', p: '想看出一个月气温的变化趋势，选哪种统计图？', v: '📈', a: '折线统计图', o: ['折线统计图', '条形统计图', '统计表', '扇形统计图'], e: '看变化趋势用折线统计图，看数量多少用条形统计图。' },
    { k: 'math-5a-04', t: '可能性', p: '袋子里有 5 个红球、1 个白球，任意摸一个，最可能摸到？', v: '🔴🔴🔴🔴🔴⚪', a: '红球', o: ['红球', '白球', '一样可能', '一定是白球'], e: '红球数量多，摸到的可能性大，但不是一定。' },
  ],
  chinese: [
    { k: 'c-pinyin', t: '声母辨析', p: '“跑 pǎo”的声母是？', v: '🏃 pāo', a: 'p', o: ['p', 'b', 'q', 'd'], e: 'pǎo的声母是p，读时双唇送气，和b（不送气）要分清。' },
    { k: 'c-pinyin', t: '整体认读', p: '下面哪个是整体认读音节？', v: '🔤', a: 'yi', o: ['yi', 'ni', 'mi', 'di'], e: 'yi是整体认读音节，要整体记住直接读，不能拼。' },
    { k: 'c-pinyin', t: '看拼音选词', p: '“shuǐ guǒ”对应哪个词？', v: '🍎 shuǐ guǒ', a: '水果', o: ['水果', '水牛', '花果', '水面'], e: 'shuǐ是水，guǒ是果，合起来是“水果”。' },
    { k: 'c-hanzi', t: '笔顺笔画', p: '“长”一共有几画？', v: '长', a: '4画', o: ['4画', '3画', '5画', '6画'], e: '“长”的笔顺是撇、横、竖提、捺，一共4画。' },
    { k: 'c-hanzi', t: '看图选汉字', p: '看图选汉字', v: '🌞', a: '日', o: ['日', '月', '天', '白'], e: '太阳圆圆像“日”字；“日”字窄、“目”字宽，别认错。' },
    { k: 'c-hanzi', t: '偏旁归类', p: '“江”“河”“湖”都有哪个偏旁？', v: '💧', a: '三点水氵', o: ['三点水氵', '木字旁木', '口字旁口', '日字旁日'], e: '江河湖都和水有关，所以都是三点水旁。' },
    { k: 'c-words', t: '数量词搭配', p: '一( )小鱼，括号里填哪个量词？', v: '🐟', a: '条', o: ['条', '只', '头', '块'], e: '鱼用“条”：一条小鱼；鸟用“只”，牛用“头”。' },
    { k: 'c-words', t: '反义词', p: '“大”的反义词是？', v: '🐘 🐜', a: '小', o: ['小', '多', '高', '长'], e: '大和小是一对反义词，像高和矮、多和少一样。' },
    { k: 'c-words', t: '词语搭配', p: '“____的太阳”，横线上填哪个词最合适？', v: '🌞', a: '红红', o: ['红红', '飞快', '悄悄', '甜甜'], e: '太阳是红红的。“飞快”形容跑步，“甜甜”形容味道。' },
    { k: 'c-words', t: '近义词', p: '“美丽”的近义词是？', v: '🌸', a: '漂亮', o: ['漂亮', '丑陋', '干净', '安静'], e: '美丽和漂亮意思相近；丑陋是反义词。' },
    { k: 'c-sentence', t: '标点符号', p: '“你叫什么名字”后面应该用什么标点？', v: '❓', a: '问号？', o: ['问号？', '句号。', '感叹号！', '逗号，'], e: '问问题用问号；说完一句话用句号；很激动用感叹号。' },
    { k: 'c-sentence', t: '完整句子', p: '哪一句是完整的句子？', v: '📝', a: '小鸟在天上飞。', o: ['小鸟在天上飞。', '天上小鸟飞在', '飞小鸟天上', '小鸟飞'], e: '完整的句子要有“谁在干什么”：小鸟（谁）在天上飞（干什么）。' },
    { k: 'c-sentence', t: '比喻句', p: '“弯弯的月亮像____”，填哪个最合适？', v: '🌙', a: '小船', o: ['小船', '太阳', '大山', '小狗'], e: '月亮弯弯的和小船最像，这是比喻句。' },
    { k: 'c-read', t: '阅读理解', p: '“小猫爱吃鱼，小狗爱啃骨头。”小猫爱吃什么？', v: '🐱 🐟', a: '鱼', o: ['鱼', '骨头', '青草', '米饭'], e: '短文里说了“小猫爱吃鱼”，答案就在文中找。' },
    { k: 'c-read', t: '古诗积累', p: '“举头望明月”的下一句是？', v: '🌙', a: '低头思故乡', o: ['低头思故乡', '粒粒皆辛苦', '春风又绿江南岸', '独在异乡为异客'], e: '这是李白的《静夜思》：举头望明月，低头思故乡。' },
    { k: 'c-read', t: '短文排序', p: '按顺序排：①开花 ②发芽 ③结果，哪组对？', v: '🌱 🌸 🍎', a: '②①③', o: ['②①③', '①②③', '③①②', '①③②'], e: '种子先发芽，再开花，最后结果：②①③。' },
    { k: 'c-speak', t: '礼貌用语', p: '别人帮助了你，你应该说？', v: '🙏', a: '谢谢！', o: ['谢谢！', '走开！', '不用你管！', '没看见吗？'], e: '得到帮助要说“谢谢”，这是有礼貌的好孩子。' },
    { k: 'c-speak', t: '看图写话', p: '小朋友扶老奶奶过马路，他做得对吗？', v: '👦 👵 🚸', a: '对，尊老且守交规', o: ['对，尊老且守交规', '不对，应该先跑', '不对，应该不管', '对，因为好玩'], e: '帮助老人过马路是尊老的表现，走斑马线也遵守了交通规则。' },
    { k: 'yuwen-3a-01', t: '查字典·音序', p: '用音序查字法查“春”，应先查大写字母？', v: '🔤 春', a: 'C', o: ['C', 'S', 'Ch', 'U'], e: '“春”的音序是C（chūn的首字母大写）。音序查字法：先找大写首字母，再找音节。' },
    { k: 'yuwen-3a-01', t: '查字典·部首', p: '“鼻”字用部首查字法，应查部首？', v: '🔤 鼻', a: '鼻（自部，6画）', o: ['鼻（自部，6画）', '鼻（鼻部，14画）', '鼻（田部，5画）', '鼻（丿部，1画）'], e: '“鼻”的部首是“自”，部首6画。除部首外还有8画。' },
    { k: 'yuwen-3a-02', t: '修辞·比喻', p: '“秋天的雨，吹起了金色的小喇叭。”用了什么修辞？', v: '🍂 📯', a: '比喻', o: ['比喻', '拟人', '排比', '夸张'], e: '把秋雨比作小喇叭，有本体（雨）和喻体（喇叭），是比喻。' },
    { k: 'yuwen-3a-06', t: '修辞·拟人', p: '“大自然在唱歌，风儿在跳舞。”用了什么修辞？', v: '🌳 🎵', a: '拟人', o: ['拟人', '比喻', '夸张', '设问'], e: '把大自然、风儿当作人来写，会唱歌跳舞，是拟人。' },
    { k: 'yuwen-5a-07', t: '修辞·排比', p: '“春天像小姑娘，花枝招展的，笑着，走着。”主要修辞是？', v: '🌸', a: '比喻和排比', o: ['比喻和排比', '只有夸张', '只有设问', '只有对偶'], e: '“像”是比喻；“笑着，走着”句式整齐，是排比。朱自清《春》常用这两种修辞。' },
    { k: 'yuwen-5b-05', t: '修辞·夸张', p: '“刷子李刷完墙，身上一个白点也没有。”主要运用了？', v: '🖌️', a: '夸张', o: ['夸张', '比喻', '拟人', '排比'], e: '“一个白点也没有”故意言过其实，突出技艺高超，是夸张。' },
    { k: 'yuwen-4a-02', t: '修辞·设问', p: '“是谁呼风唤雨呢？当然是人类。”用了什么修辞？', v: '❓', a: '设问', o: ['设问', '反问', '比喻', '夸张'], e: '自问自答叫设问；只问不答、用问句表肯定叫反问。' },
    { k: 'yuwen-3b-05', t: '扩句', p: '给“小鱼游”扩句，哪一项扩得最合适？', v: '🐟', a: '可爱的小鱼在水里快活地游来游去。', o: ['可爱的小鱼在水里快活地游来游去。', '小鱼游游游。', '鱼游。', '小鱼不游。'], e: '扩句要加定语、状语，让句子具体生动：什么样的、在哪儿、怎么样。' },
    { k: 'yuwen-4a-06', t: '缩句', p: '“可爱的小姑娘抱着洋娃娃。”缩句后是？', v: '👧', a: '小姑娘抱着洋娃娃。', o: ['小姑娘抱着洋娃娃。', '小姑娘。', '抱着。', '可爱的抱着洋娃娃。'], e: '缩句去“枝叶”留主干：谁（小姑娘）干什么（抱着洋娃娃）。' },
    { k: 'yuwen-4b-06', t: '修改病句', p: '“经过努力，我的成绩提高了水平。”应怎么改？', v: '📝', a: '把“水平”改为“了”或删去“水平”', o: ['把“水平”改为“了”或删去“水平”', '把“努力”删去', '把“成绩”改为“学习”', '不用改'], e: '“提高”后面不能接“水平”，搭配不当：改为“我的成绩提高了”。' },
    { k: 'yuwen-5a-05', t: '修改病句', p: '“全班同学都到了，只有小明还没到。”毛病是？', v: '📝', a: '前后矛盾', o: ['前后矛盾', '用词重复', '缺少主语', '语序颠倒'], e: '“都到了”又说“还没到”，自相矛盾：改为“全班同学到了，只有小明还没到。”' },
    { k: 'yuwen-4b-06', t: '关联词', p: '“（ ）刮风下雨，运动会（ ）照常举行。”填哪组关联词？', v: '🌧️ 🏃', a: '即使……也……', o: ['即使……也……', '因为……所以……', '如果……就……', '不但……而且……'], e: '前后是让步关系：即使刮风下雨，也照常举行。用“即使……也……”。' },
    { k: 'yuwen-5a-06', t: '转述句', p: '把“妈妈对我说：‘你要好好学习。’”改为转述句是？', v: '💬', a: '妈妈对我说，我要好好学习。', o: ['妈妈对我说，我要好好学习。', '妈妈对我说：“你要好好学习。”', '妈妈说你要好好学习。', '妈妈对我说，你要好好学习。'], e: '转述句去冒号引号，人称跟着变：“你”→“我”。注意标点改成逗号句号。' },
    { k: 'yuwen-3b-03', t: '多音字', p: '“赵州桥” 的“州”，还读什么音组什么词？', v: '🌉', a: 'zhōu：广州', o: ['zhōu：广州', 'zhòu：姓周', 'yóu：游泳', 'chóu：报仇'], e: '“州”读zhōu，如赵州桥、广州、杭州。别读成zhòu（周）。' },
    { k: 'yuwen-3b-06', t: '近义词辨析', p: '“注视”和“凝视”都表示看，哪个程度更深？', v: '👀', a: '凝视', o: ['凝视', '注视', '一样深', '都不深'], e: '凝视是聚精会神、长时间地看，程度比注视更深。' },
    { k: 'yuwen-4a-05', t: '阅读·概括', p: '读完《麻雀》，用一句话概括主要内容，最合适的是？', v: '🐦', a: '老麻雀奋不顾身地拯救小麻雀。', o: ['老麻雀奋不顾身地拯救小麻雀。', '我打猎回来。', '小麻雀掉在地上。', '猎狗很凶猛。'], e: '概括抓住“谁干什么”：老麻雀（谁）拯救小麻雀（干什么）。' },
    { k: 'yuwen-5a-02', t: '阅读·含义', p: '《少年中国说》“美哉我少年中国”表达了作者什么感情？', v: '🇨🇳', a: '对祖国未来的热爱与期望', o: ['对祖国未来的热爱与期望', '对山水的喜爱', '思念家乡', '喜欢少年'], e: '梁启超把祖国的未来寄托在少年身上，充满热爱与期望。' },
    { k: 'yuwen-5a-04', t: '阅读·说明方法', p: '“太阳离我们约1.5亿公里。”用了什么说明方法？', v: '☀️', a: '列数字', o: ['列数字', '打比方', '作比较', '举例子'], e: '用具体数字“1.5亿公里”来说明，就是列数字。' },
    { k: 'yuwen-6a-06', t: '阅读·联系实际', p: '读了《只有一个地球》，我们应该怎么做？', v: '🌍', a: '节约资源，保护环境', o: ['节约资源，保护环境', '多用一次性用品', '浪费水电', '乱扔垃圾'], e: '地球可爱又易碎，联系实际：从节约一张纸、一滴水做起。' },
    { k: 'yuwen-3b-01', t: '古诗·写景', p: '“迟日江山丽，春风花草香。”描写的是哪个季节？', v: '🌸', a: '春季', o: ['春季', '夏季', '秋季', '冬季'], e: '杜甫《绝句》：江山丽、花草香，写的是生机勃勃的春天。' },
    { k: 'yuwen-4a-03', t: '古诗·哲理', p: '“不识庐山真面目”的下一句是？', v: '⛰️', a: '只缘身在此山中', o: ['只缘身在此山中', '一览众山小', '疑是银河落九天', '春风又绿江南岸'], e: '苏轼《题西林壁》：不识庐山真面目，只缘身在此山中。讲当局者迷的道理。' },
    { k: 'yuwen-4a-03', t: '古诗·梅', p: '“墙角数枝梅”的下一句是？', v: '🌸 ❄️', a: '凌寒独自开', o: ['凌寒独自开', '暗香浮动月黄昏', '宝剑锋从磨砺出', '梅须逊雪三分白'], e: '卢钺《雪梅》：墙角数枝梅，凌寒独自开。赞美梅花不畏严寒。' },
    { k: 'yuwen-5a-02', t: '古诗·爱国', p: '“王师北定中原日”的下一句是？', v: '🇨🇳', a: '家祭无忘告乃翁', o: ['家祭无忘告乃翁', '感时花溅泪', '了却君王天下事', '人生自古谁无死'], e: '陆游《示儿》：王师北定中原日，家祭无忘告乃翁。临终不忘祖国统一。' },
    { k: 'yuwen-6a-02', t: '古诗·长征', p: '“红军不怕远征难”的下一句是？', v: '🚩', a: '万水千山只等闲', o: ['万水千山只等闲', '更喜岷山千里雪', '三军过后尽开颜', '乌蒙磅礴走泥丸'], e: '毛泽东《七律·长征》：红军不怕远征难，万水千山只等闲。表现革命乐观主义。' },
    { k: 'yuwen-6b-01', t: '古诗·民俗', p: '“爆竹声中一岁除”的下一句是？', v: '🧨', a: '春风送暖入屠苏', o: ['春风送暖入屠苏', '总把新桃换旧符', '千门万户曈曈日', '爆竹声中一岁除'], e: '王安石《元日》：爆竹声中一岁除，春风送暖入屠苏。写春节习俗。' },
    { k: 'yuwen-3a-07', t: '小古文', p: '《司马光》中“众皆弃去”的意思是？', v: '📜', a: '大家都离开了', o: ['大家都离开了', '大家都扔石头', '大家都哭了', '大家都去玩了'], e: '“弃去”就是丢下离开：小伙伴们都吓跑了，只有司马光砸缸救人。' },
    { k: 'yuwen-5b-08', t: '小古文', p: '《杨氏之子》中“甚聪惠”的意思是？', v: '📜', a: '非常聪明', o: ['非常聪明', '很会画画', '很懂礼貌', '很爱读书'], e: '“惠”通“慧”：杨氏子九岁，甚聪惠。表现他的机智。' },
    { k: 'yuwen-6b-04', t: '小古文', p: '《学弈》中两个人学下棋结果不同，是因为？', v: '♟️', a: '学习态度不同', o: ['学习态度不同', '老师偏心', '棋艺天赋不同', '时间长短不同'], e: '一人专心致志，一人三心二意：学习态度决定结果。' },
    { k: 'yuwen-3a-09', t: '习作·审题', p: '习作题目是《我的课余生活》，下面哪个选材最合适？', v: '✏️', a: '周末学骑自行车', o: ['周末学骑自行车', '介绍我的学校', '描写秋天的树叶', '写我的同桌'], e: '审题先看清要求：课余生活，选课余时间做的事来写。' },
    { k: 'yuwen-4a-09', t: '习作·观察', p: '写观察日记，最重要的是？', v: '🔍 📝', a: '连续观察，记录变化', o: ['连续观察，记录变化', '一次看完就写', '抄别人的', '只写结果不写过程'], e: '观察日记要连续多天看，记下变化和发现，写出真情实感。' },
    { k: 'yuwen-5b-05', t: '习作·写人', p: '写一个有特点的人，最好的方法是？', v: '👤 ✏️', a: '通过一两件事写出特点', o: ['通过一两件事写出特点', '只写外貌', '罗列很多优点', '抄作文书'], e: '写人要以事带人：一两件具体的事 + 语言动作神态细节。' },
    { k: 'yuwen-6b-06', t: '习作·开头', p: '写《难忘的一件事》，哪种开头最好？', v: '✏️', a: '开门见山或设置悬念', o: ['开门见山或设置悬念', '先抄一段名言凑字数', '从很久以前 unrelated 说起', '重复题目三遍'], e: '好开头：开门见山点题，或设悬念吸引人。凤头要小而精。' },
    { k: 'yuwen-4b-07', t: '成语积累', p: '“守株待兔”比喻？', v: '🐇 🌳', a: '死守经验，不知变通', o: ['死守经验，不知变通', '比赛跑步', '爱护动物', '种树有功'], e: '守株待兔：比喻死守狭隘经验，不知变通。' },
    { k: 'yuwen-5b-02', t: '歇后语', p: '“周瑜打黄盖”的下一句是？', v: '📖', a: '一个愿打，一个愿挨', o: ['一个愿打，一个愿挨', '赔了夫人又折兵', '万事俱备，只欠东风', '说曹操，曹操到'], e: '出自《三国演义》草船借箭前后故事：愿打愿挨。' },
    { k: 'yuwen-5b-02', t: '名著人物', p: '《景阳冈》的主人公是谁？', v: '🐯 🍷', a: '武松', o: ['武松', '鲁智深', '林冲', '李逵'], e: '武松景阳冈打虎，是《水浒传》的经典情节。' },
    { k: 'yuwen-6b-02', t: '名著阅读', p: '《鲁滨逊漂流记》的作者是哪个国家的？', v: '🏝️', a: '英国', o: ['英国', '法国', '美国', '德国'], e: '笛福是英国作家。鲁滨逊在荒岛生活28年，表现乐观坚毅。' },
    { k: 'yuwen-3b-03', t: '传统文化', p: '造纸术是我国古代哪大发明之一？', v: '📜', a: '四大发明', o: ['四大发明', '三大发明', '五大发明', '两大发明'], e: '四大发明：造纸术、印刷术、火药、指南针。蔡伦改进了造纸术。' },
  ],
  english: [
    { k: 'e-alpha', t: '字母认读', p: 'Apple（苹果）的首字母是？', v: '🍎 Apple', a: 'A', o: ['A', 'B', 'C', 'E'], e: 'Apple以A开头，大写A、小写a都要认得。' },
    { k: 'e-alpha', t: '字母顺序', p: '按字母表顺序，C 后面是？', v: '🔤 A B C ?', a: 'D', o: ['D', 'E', 'B', 'F'], e: '字母表顺序是 …B C D E…，C后面是D。' },
    { k: 'e-alpha', t: '大小写配对', p: '大写 G 对应的小写是？', v: 'G → ?', a: 'g', o: ['g', 'j', 'q', '9'], e: 'G的小写是g，注意和j、q区分。' },
    { k: 'e-phonics', t: '首字母发音', p: '哪个单词是以 /b/ 开头的？', v: '🔊 /b/', a: 'Ball 球', o: ['Ball 球', 'Cat 猫', 'Dog 狗', 'Egg 蛋'], e: 'Ball读作/bɔːl/，开头是/b/的音。' },
    { k: 'e-phonics', t: '听音辨词', p: '“red”表示什么颜色？', v: '🔴 red', a: '红色', o: ['红色', '蓝色', '绿色', '黄色'], e: 'red红色；blue蓝色；green绿色；yellow黄色。' },
    { k: 'e-words', t: '动物单词', p: '“小猫”用英语怎么说？', v: '🐱', a: 'cat', o: ['cat', 'dog', 'pig', 'cow'], e: 'cat是猫，dog是狗，pig是猪，cow是奶牛。' },
    { k: 'e-words', t: '数字单词', p: '“三”用英语怎么说？', v: '3️⃣', a: 'three', o: ['three', 'two', 'tree', 'free'], e: 'three是三（th要咬舌），two是二，别和tree（树）搞混。' },
    { k: 'e-words', t: '身体部位', p: '“眼睛”用英语怎么说？', v: '👀', a: 'eye', o: ['eye', 'ear', 'nose', 'mouth'], e: 'eye眼睛，ear耳朵，nose鼻子，mouth嘴巴。' },
    { k: 'e-words', t: '食物单词', p: '“香蕉”用英语怎么说？', v: '🍌', a: 'banana', o: ['banana', 'apple', 'orange', 'pear'], e: 'banana是香蕉，黄黄弯弯的。' },
    { k: 'e-words', t: '家庭成员', p: '“妈妈”用英语怎么说？', v: '👩', a: 'mother', o: ['mother', 'father', 'sister', 'brother'], e: 'mother妈妈，father爸爸，sister姐妹，brother兄弟。' },
    { k: 'e-daily', t: '问候语', p: '早上见到老师，应该说？', v: '🌅', a: 'Good morning!', o: ['Good morning!', 'Good night!', 'Goodbye!', 'Sorry!'], e: '早上好是Good morning；晚安Good night；再见Goodbye。' },
    { k: 'e-daily', t: '感谢用语', p: '别人送你礼物，你说？', v: '🎁', a: 'Thank you!', o: ['Thank you!', 'Hello!', 'No!', 'Come on!'], e: '收到礼物或帮助要说Thank you（谢谢你）！' },
    { k: 'e-daily', t: '自我介绍', p: '“我叫明明。”用英语怎么说？', v: '👦', a: 'My name is Mingming.', o: ['My name is Mingming.', 'I am fine.', 'How are you?', 'I like apples.'], e: '介绍名字用句型：My name is + 名字。' },
    { k: 'e-daily', t: '简单问答', p: '—How are you? —______ 怎么回答？', v: '💬', a: 'I’m fine, thank you.', o: ['I’m fine, thank you.', 'Goodbye.', 'My name is Tom.', 'I am six.'], e: '问“How are you（你好吗）”，回答“I’m fine, thank you（我很好，谢谢）”。' },
    { k: 'eng-3a-02', t: '拼读规则', p: '单词 cake 中 a 的发音是？', v: '🍰 cake', a: '/eɪ/（A的本音）', o: ['/eɪ/（A的本音）', '/æ/（短音）', '/ɑː/', '不发音'], e: 'a-e 结构中 a 发本音/eɪ/：cake, name, lake 都是这样。' },
    { k: 'eng-3a-04', t: '拼读规则', p: 'duck 中 ck 的发音是？', v: '🦆 duck', a: '/k/', o: ['/k/', '/s/', '/tʃ/', '/g/'], e: 'ck 组合发/k/：duck（鸭子）、black（黑色）、clock（钟）。' },
    { k: 'eng-3b-05', t: '拼读规则', p: 'three 中 th 的发音方法是？', v: '3️⃣ three', a: '咬舌发/θ/', o: ['咬舌发/θ/', '发/s/', '发/t/', '不发音'], e: 'th 在 three、thank 中咬舌发/θ/，舌尖轻触上齿。' },
    { k: 'eng-4a-01', t: 'be动词', p: '______ is my classroom. 横线处填？', v: '🏫', a: 'This', o: ['This', 'These', 'Those', 'They'], e: '介绍单数近处用 This is…；复数用 These are…。' },
    { k: 'eng-4a-01', t: 'be动词', p: 'Where ______ my shoes? 横线处填？', v: '👟', a: 'are', o: ['are', 'is', 'am', 'be'], e: 'shoes 是复数，be 动词用 are。口诀：我用am，你用are，is连着他她它，复数后面are。' },
    { k: 'eng-5a-01', t: '第三人称单数', p: 'He ______ TV every day. 横线处填？', v: '📺', a: 'watches', o: ['watches', 'watch', 'watching', 'watched'], e: '主语是第三人称单数 he，动词要加 s/es：watch→watches。' },
    { k: 'eng-5a-04', t: '情态动词can', p: 'She can ______ very well. 横线处填？', v: '🏊', a: 'swim', o: ['swim', 'swims', 'swimming', 'swam'], e: 'can 后面永远跟动词原形：can swim（会游泳）。' },
    { k: 'eng-5a-05', t: 'there be句型', p: '______ a book and two pens on the desk. 横线处填？', v: '📚', a: 'There is', o: ['There is', 'There are', 'There be', 'It is'], e: 'there be 就近原则：离得近的是 a book（单数），用 There is。' },
    { k: 'eng-5b-06', t: '现在进行时', p: 'Look! The boy ______ now. 横线处填？', v: '🏃', a: 'is running', o: ['is running', 'runs', 'run', 'ran'], e: 'Look! 提示正在发生：be + 动词ing。run 双写 n 加 ing。' },
    { k: 'eng-6b-02', t: '一般过去时', p: 'I ______ TV last night. 横线处填？', v: '📺 🌙', a: 'watched', o: ['watched', 'watch', 'watches', 'watching'], e: 'last night 是过去时间标志，动词用过去式：watch→watched。' },
    { k: 'eng-6b-03', t: '不规则过去式', p: 'We ______ to the park yesterday. 横线处填？', v: '🏞️', a: 'went', o: ['went', 'go', 'goes', 'going'], e: 'go 的过去式是 went（不规则变化，要死记）：go-went-gone。' },
    { k: 'eng-6b-04', t: 'was/were', p: 'There ______ no library in my school ten years ago. 横线处填？', v: '🏫', a: 'was', o: ['was', 'were', 'is', 'are'], e: 'ago 是过去，主语 library 单数：用 was。复数用 were。' },
    { k: 'eng-3b-06', t: 'How many', p: '—______ apples? —Five. 问句是？', v: '🍎🍎🍎🍎🍎', a: 'How many', o: ['How many', 'How much', 'How old', 'How long'], e: '数个数用 How many + 可数名词复数；问价钱用 How much。' },
    { k: 'eng-4b-06', t: '购物交际', p: '—Can I help you? —______ 答句是？', v: '🛍️', a: 'Yes. I’d like a pair of shoes.', o: ['Yes. I’d like a pair of shoes.', 'I’m fine.', 'Goodbye.', 'Thank you. No.'], e: '店员问“需要帮忙吗”，回答想要的东西：I’d like…（我想要……）。' },
    { k: 'eng-6a-01', t: '问路交际', p: '—______ can I get to the park? —Go straight. 问句是？', v: '🗺️ 🏞️', a: 'How', o: ['How', 'What', 'Where', 'When'], e: '问“怎么去”用 How：How can I get there? 回答 Go straight（直走）。' },
    { k: 'eng-6a-06', t: '情绪建议', p: '—I feel ill. —______ 回答是？', v: '🤒', a: 'You should see a doctor.', o: ['You should see a doctor.', 'Great!', 'Me too.', 'Goodbye.'], e: '给建议用 should：You should see a doctor（你应该去看医生）。' },
    { k: 'eng-4b-02', t: '时间表达', p: '“3点半”用英语说是？', v: '🕞', a: 'half past three', o: ['half past three', 'three past half', 'half three', 'three thirty past'], e: '半点用 half past + 整点：half past three = 3:30。' },
    { k: 'eng-6a-05', t: '职业词汇', p: '在医院工作、给人看病的是？', v: '🏥', a: 'doctor', o: ['doctor', 'teacher', 'farmer', 'driver'], e: 'doctor医生，teacher老师，farmer农民，driver司机。' },
    { k: 'eng-5b-02', t: '季节活动', p: '冬天人们常进行的活动是？', v: '❄️', a: 'go skating', o: ['go skating', 'go swimming', 'fly kites', 'plant trees'], e: '冬天滑冰 go skating；夏天游泳 go swimming；春天放风筝 fly kites。' },
    { k: 'eng-5b-03', t: '月份', p: '一年中的第一个月是？', v: '📅', a: 'January', o: ['January', 'December', 'March', 'June'], e: 'January一月，December十二月。月份首字母永远大写。' },
    { k: 'eng-6b-01', t: '比较级', p: 'My brother is ______ than me. 横线处填？', v: '📏', a: 'taller', o: ['taller', 'tall', 'tallest', 'more tall'], e: '有 than 就用比较级：tall→taller。短单词直接加 er。' },
    { k: 'eng-4b-04', t: 'these/those', p: '______ are sheep.（指着远处的羊）横线处填？', v: '🐑 🐑', a: 'Those', o: ['Those', 'These', 'This', 'That'], e: '远处复数用 Those；近处复数用 These。sheep 单复数同形。' },
    { k: 'eng-5a-02', t: '频度副词', p: '“我通常周末打篮球。”often 的位置是？', v: '🏀', a: 'I often play basketball on weekends.', o: ['I often play basketball on weekends.', 'I play often basketball on weekends.', 'Often I play basketball on weekends always.', 'I play basketball often on weekends always.'], e: '频度副词 often 放行为动词前面：I often play…。' },
    { k: 'eng-5b-04', t: '日期表达', p: '“6月1日”用英语说是？', v: '🎈 6.1', a: 'June 1st', o: ['June 1st', 'June 1th', 'June one', '1st June only'], e: '1日用 1st（first），2日 2nd，3日 3rd，其他 th：June 1st。' },
    { k: 'eng-6a-03', t: 'be going to', p: 'I ______ visit my grandparents this weekend. 横线处填？', v: '👴 👵', a: 'am going to', o: ['am going to', 'am going', 'goes to', 'going to am'], e: '表计划用 be going to：主语 I 配 am → am going to do。' },
    { k: 'eng-5b-01', t: '短文阅读', p: '“Mike gets up at 6:30. He has breakfast at 7:00.” Mike 几点吃早饭？', v: '🍳', a: '7:00', o: ['7:00', '6:30', '7:30', '6:00'], e: 'has breakfast 就是吃早饭：at 7:00。gets up 是起床。' },
    { k: 'eng-6a-04', t: '短文阅读', p: '“Lucy likes reading stories. Her hobby is reading.” Lucy 的爱好是？', v: '📚', a: 'reading stories', o: ['reading stories', 'swimming', 'dancing', 'singing'], e: 'hobby 就是爱好：reading stories（读故事）。like doing 喜欢做某事。' },
    { k: 'eng-6b-03', t: '短文阅读', p: '“Last Sunday Tom went to the zoo. He saw elephants.” Tom 上周日去哪了？', v: '🐘', a: 'the zoo', o: ['the zoo', 'the park', 'the school', 'the farm'], e: 'went to the zoo 就是去了动物园。went 是 go 的过去式。' },
  ],
  science: [
    { k: 's-plant', t: '生长需要', p: '植物制造养分需要什么？', v: '🌱', a: '阳光', o: ['阳光', '月亮', '雪', '黑暗'], e: '植物靠阳光进行光合作用制造养分。' },
    { k: 's-plant', t: '种子发芽', p: '种子发芽通常需要什么？', v: '🌰 → 🌱', a: '水和适宜的温度', o: ['水和适宜的温度', '油和冰块', '只有石头', '干燥寒冷'], e: '种子发芽需要水、空气和适宜的温度。' },
    { k: 's-plant', t: '植物部位', p: '吸收水分的是植物的哪个部位？', v: '🌳', a: '根', o: ['根', '花', '叶', '果实'], e: '根在土里吸收水分和养料，叶进行光合作用。' },
    { k: 's-animal', t: '动物习性', p: '哪一种动物会冬眠？', v: '🐻 ❄️', a: '熊', o: ['熊', '鸡', '鱼', '麻雀'], e: '熊冬天睡大觉叫冬眠，靠秋天储存的脂肪过冬。' },
    { k: 's-animal', t: '呼吸方式', p: '哪种动物用鳃呼吸？', v: '🐟', a: '鱼', o: ['鱼', '猫', '鸟', '狗'], e: '鱼用鳃在水里呼吸，猫狗用肺呼吸。' },
    { k: 's-animal', t: '运动方式', p: '青蛙主要靠什么运动？', v: '🐸', a: '跳跃和游泳', o: ['跳跃和游泳', '飞翔', '爬行滑行', '奔跑'], e: '青蛙后腿发达会跳，脚趾间有蹼会游泳。' },
    { k: 's-body', t: '认识身体', p: '人的心脏在哪里？', v: '🫀', a: '胸腔', o: ['胸腔', '手掌', '脚底', '头顶'], e: '心脏在胸腔里左边，不停跳动输送血液。' },
    { k: 's-body', t: '感官作用', p: '我们用哪个器官闻气味？', v: '👃 🌸', a: '鼻子', o: ['鼻子', '耳朵', '眼睛', '舌头'], e: '鼻子闻气味，耳朵听声音，眼睛看东西，舌头尝味道。' },
    { k: 's-matter', t: '物质变化', p: '水结冰后会变成什么？', v: '💧 → 🧊', a: '冰', o: ['冰', '沙子', '烟', '糖'], e: '水在0℃以下会结成冰，加热又会化成水。' },
    { k: 's-matter', t: '空气特点', p: '给气球打气，气球变大说明？', v: '🎈', a: '空气占据空间', o: ['空气占据空间', '气球会变色', '空气有颜色', '气球变重了'], e: '空气看不见摸不着，但它占据空间，能把气球撑大。' },
    { k: 's-light', t: '光与影', p: '影子通常在什么时候出现？', v: '🌞 🧍', a: '有光时', o: ['有光时', '完全黑暗时', '闭眼时', '下雨天'], e: '有光照着不透明的物体，才会有影子。' },
    { k: 's-light', t: '昼夜成因', p: '白天和黑夜交替是因为？', v: '🌍 ☀️', a: '地球在自转', o: ['地球在自转', '太阳在跑步', '月亮休息了', '云朵遮住了'], e: '地球不停自转，转到对着太阳就是白天，转过去就是黑夜。' },
    { k: 's-weather', t: '天气观察', p: '下雨前天空常出现什么？', v: '🌧️', a: '乌云', o: ['乌云', '彩虹', '星星', '月亮'], e: '乌云又厚又黑，常常带来降雨；雨后才有彩虹。' },
    { k: 's-weather', t: '四季特点', p: '哪个季节最冷，会下雪？', v: '❄️', a: '冬季', o: ['冬季', '春季', '夏季', '秋季'], e: '春暖、夏热、秋凉、冬冷，冬天下雪可以堆雪人。' },
    { k: 'sci-4b-01', t: '简单电路', p: '一个简单电路必须包括？', v: '🔋 💡', a: '电源、导线、用电器', o: ['电源、导线、用电器', '只有电池', '只有灯泡', '只需要导线'], e: '电路三件套：电池（电源）、导线、灯泡（用电器），缺一不可。' },
    { k: 'sci-4b-01', t: '导体绝缘体', p: '下面哪个是导体，能让灯泡亮起来？', v: '🔌', a: '铁丝', o: ['铁丝', '塑料尺', '干木棍', '橡皮'], e: '金属是导体：铁丝、铜丝能导电；塑料、木头、橡皮是绝缘体。' },
    { k: 'sci-4b-01', t: '安全用电', p: '下面哪种做法是安全的？', v: '⚡', a: '不用湿手触摸电器', o: ['不用湿手触摸电器', '用湿手插插头', '把铁丝伸进插座', '同时使用太多大功率电器'], e: '水能导电，湿手摸电器非常危险。记住：安全用电，人人有责。' },
    { k: 'sci-3b-04', t: '磁极', p: '磁铁能吸住哪种物品？', v: '🧲', a: '铁钉', o: ['铁钉', '塑料积木', '木块', '纸片'], e: '磁铁吸铁、钴、镍：铁钉可以，塑料木头纸都不行。' },
    { k: 'sci-3b-04', t: '磁极作用', p: '两块磁铁的 N 极靠近，会怎么样？', v: '🧲 ↔️ 🧲', a: '互相排斥', o: ['互相排斥', '互相吸引', '没有反应', '粘在一起'], e: '同极相斥、异极相吸：N对N排斥，N对S吸引。' },
    { k: 'sci-5a-01', t: '光的传播', p: '光在空气中是怎样传播的？', v: '🔦', a: '沿直线传播', o: ['沿直线传播', '沿曲线传播', '向四周拐弯', '静止不动'], e: '光沿直线传播：影子、小孔成像、日食月食都证明了这点。' },
    { k: 'sci-5a-01', t: '光的反射', p: '晚上用手电照镜子，光会？', v: '🪞 🔦', a: '被镜子反射回来', o: ['被镜子反射回来', '穿过镜子', '被镜子吸收', '消失不见'], e: '光遇到镜子会反射：镜子、平静水面都能照出影子。' },
    { k: 'sci-5b-01', t: '沉浮', p: '把一块木头放入水中，它会？', v: '🪵 💧', a: '浮在水面', o: ['浮在水面', '沉到水底', '悬在中间', '慢慢溶解'], e: '木头比水轻，受到的浮力大，会浮在水面。铁块则会下沉。' },
    { k: 'sci-5b-02', t: '热传递', p: '端起一杯热水，手感到热，主要是因为？', v: '☕', a: '热传到了手上', o: ['热传到了手上', '杯子在动', '手自己发热', '眼睛看到了热'], e: '热从高温物体传到低温物体，叫热传递：传导、对流、辐射。' },
    { k: 'sci-5b-04', t: '昼夜交替', p: '地球上出现昼夜交替的主要原因是？', v: '🌍 ☀️', a: '地球自转', o: ['地球自转', '地球公转', '月球自转', '太阳运动'], e: '地球自西向东自转，转一圈约24小时，带来昼夜交替。' },
    { k: 'sci-5b-04', t: '月相变化', p: '农历十五前后，我们看到的月亮通常是？', v: '🌕', a: '满月（圆月）', o: ['满月（圆月）', '娥眉月', '上弦月', '看不到月亮'], e: '十五前后是满月；初一前后是新月（看不到）。月相每月循环一次。' },
    { k: 'sci-6b-03', t: '太阳系', p: '离太阳最近的行星是？', v: '☀️ 🪐', a: '水星', o: ['水星', '金星', '地球', '火星'], e: '按离太阳从近到远：水、金、地、火、木、土、天、海。' },
    { k: 'sci-6a-01', t: '杠杆', p: '用撬棍撬石头，撬棍属于？', v: '🪨 🥢', a: '杠杆', o: ['杠杆', '滑轮', '斜面', '轮轴'], e: '撬棍、剪刀、筷子都是杠杆：有支点、动力点、阻力点。' },
    { k: 'sci-6a-04', t: '食物链', p: '“草 → 兔子 → 狐狸”中，生产者是？', v: '🌱 🐇 🦊', a: '草', o: ['草', '兔子', '狐狸', '都没有'], e: '植物能制造养料，是生产者；动物是消费者。食物链从生产者开始。' },
    { k: 'sci-6b-04', t: '物质变化', p: '铁锅生锈，属于什么变化？', v: '🍳', a: '化学变化', o: ['化学变化', '物理变化', '没有变化', '状态变化'], e: '生锈生成了新物质（铁锈），是化学变化；水结冰只是形态变，是物理变化。' },
  ],
  life: [
    { k: 'l-safety', t: '交通安全', p: '过马路应该走哪里？', v: '🚦', a: '斑马线', o: ['斑马线', '花坛里', '车道中间', '哪里都行'], e: '过马路走斑马线，看红绿灯，红灯停绿灯行。' },
    { k: 'l-safety', t: '求助电话', p: '发现火灾应该拨打什么电话？', v: '🔥', a: '119', o: ['119', '120', '114', '110'], e: '119是火警，120是急救，110是报警，都要记住。' },
    { k: 'l-safety', t: '居家安全', p: '一个人在家，有陌生人敲门怎么办？', v: '🚪', a: '不开门，告诉家长', o: ['不开门，告诉家长', '马上开门', '跟他走', '假装没听见一直等'], e: '陌生人敲门不开门，可以给爸爸妈妈打电话。' },
    { k: 'l-safety', t: '乘车安全', p: '乘车时应该怎么做？', v: '🚙', a: '系安全带', o: ['系安全带', '把手伸出窗外', '车内奔跑', '大声吵闹'], e: '坐车系好安全带，不把头手伸出窗外。' },
    { k: 'l-health', t: '卫生习惯', p: '饭前要做什么？', v: '🧼', a: '洗手', o: ['洗手', '跑步', '睡觉', '看电视'], e: '饭前便后要洗手，用七步洗手法洗干净。' },
    { k: 'l-health', t: '保护眼睛', p: '怎样保护眼睛？', v: '👀', a: '保持阅读距离', o: ['保持阅读距离', '躺着看书', '关灯看书', '长时间看电视'], e: '读书眼睛离书一尺远，不躺着、不在暗处看书。' },
    { k: 'l-health', t: '健康作息', p: '小学生每天应该怎么做？', v: '😴', a: '早睡早起不熬夜', o: ['早睡早起不熬夜', '熬夜玩游戏', '早上不起床', '不吃早饭'], e: '早睡早起身体好，还要好好吃早饭。' },
    { k: 'l-manners', t: '课堂规则', p: '上课想发言应该怎么做？', v: '🙋', a: '先举手再发言', o: ['先举手再发言', '直接大声喊', '离开座位', '和同桌说话'], e: '想发言先举手，老师请你再说，这是课堂规则。' },
    { k: 'l-manners', t: '分享合作', p: '只有一个玩具，好朋友也想玩，怎么办？', v: '🧸', a: '轮流玩，一起玩', o: ['轮流玩，一起玩', '藏起来不给', '推开他', '扔掉玩具'], e: '好东西要分享，轮流玩、一起玩最开心。' },
    { k: 'l-love', t: '爱国常识', p: '每周一学校升旗时，我们应该怎么做？', v: '🇨🇳', a: '立正敬礼，大声唱国歌', o: ['立正敬礼，大声唱国歌', '跑来跑去', '低头说话', '坐在地上'], e: '升国旗要立正、敬礼，大声唱国歌，这是爱国的表现。' },
    { k: 'l-love', t: '传统节日', p: '吃月饼、赏月亮的是哪个节日？', v: '🥮 🌕', a: '中秋节', o: ['中秋节', '春节', '端午节', '儿童节'], e: '中秋节吃月饼赏月；端午节吃粽子；春节吃饺子放鞭炮。' },
    { k: 'l-love', t: '环保节约', p: '看到水龙头没关紧在滴水，你应该？', v: '🚰', a: '关紧水龙头', o: ['关紧水龙头', '不管它', '玩水', '把水开更大'], e: '水是很宝贵的资源，看到浪费要制止，养成节约的好习惯。' },
    { k: 'ddf-6a-04', t: '宪法常识', p: '我国的根本大法是？', v: '📕 ⚖️', a: '宪法', o: ['宪法', '民法典', '刑法', '班规'], e: '宪法是国家的根本大法，具有最高的法律效力。' },
    { k: 'ddf-6a-02', t: '公民义务', p: '下面哪一项是公民的义务？', v: '🇨🇳', a: '遵守法律法规', o: ['遵守法律法规', '随地吐痰', '破坏公物', '闯红灯'], e: '权利和义务是一致的：享受权利，也要遵守法律、爱护公物。' },
    { k: 'ddf-4b-02', t: '诚信', p: '答应同学的事做不到，应该怎么办？', v: '🤝', a: '提前说明原因，另约时间', o: ['提前说明原因，另约时间', '假装忘记', '撒谎找借口', '不再理同学'], e: '诚信就是说到做到；做不到要及时说明、道歉并补救。' },
    { k: 'ddf-4b-02', t: '诚信考试', p: '考试时遇到不会的题，正确的做法是？', v: '📝', a: '独立思考，不作弊', o: ['独立思考，不作弊', '偷看同桌', '传纸条', '用手机搜答案'], e: '诚信考试最光荣，作弊得来的分数没有意义。' },
    { k: 'ddf-4a-03', t: '网络安全', p: '网友约你一个人见面，你应该？', v: '💻 ⚠️', a: '拒绝并告诉家长老师', o: ['拒绝并告诉家长老师', '一个人去见面', '先要对方照片再说', '约到家里见'], e: '绝不见网友：不透露姓名学校地址，遇到要求见面立刻告诉大人。' },
    { k: 'ddf-4a-03', t: '辨别信息', p: '看到“点链接免费领游戏皮肤”，你应该？', v: '🎮 ⚠️', a: '不点，可能是诈骗', o: ['不点，可能是诈骗', '马上点开领取', '转发给全班', '输入家长手机验证码'], e: '天上不会掉馅饼：陌生链接不点、不输验证码，告诉家长。' },
    { k: 'ddf-2b-03', t: '垃圾分类', p: '吃剩的香蕉皮属于什么垃圾？', v: '🍌 🗑️', a: '厨余垃圾', o: ['厨余垃圾', '可回收物', '有害垃圾', '其他垃圾'], e: '香蕉皮、剩饭菜是厨余垃圾；废电池是有害垃圾，要分开投放。' },
    { k: 'ddf-2b-03', t: '垃圾分类', p: '废旧电池应该扔进？', v: '🔋 🗑️', a: '有害垃圾桶（红色）', o: ['有害垃圾桶（红色）', '厨余垃圾桶（绿色）', '可回收桶（蓝色）', '随便哪个桶'], e: '废电池污染土壤和水，是有害垃圾，投红色桶。' },
    { k: 'ddf-2a-01', t: '传统节日', p: '端午节是为了纪念谁？', v: '🐉', a: '屈原', o: ['屈原', '李白', '杜甫', '孔子'], e: '端午节吃粽子、赛龙舟，纪念爱国诗人屈原。' },
    { k: 'ddf-5a-04', t: '传统文化', p: '下面哪一项属于传统文化？', v: '🏮', a: '京剧', o: ['京剧', '街舞', '电子游戏', '英语演讲'], e: '京剧是国粹；书法、剪纸、中医也都是传统文化瑰宝。' },
    { k: 'ddf-6a-01', t: '情绪管理', p: '考试没考好很生气，合适的做法是？', v: '😤', a: '深呼吸冷静，分析错题', o: ['深呼吸冷静，分析错题', '撕掉卷子', '对同学发脾气', '以后再也不学了'], e: '情绪管理三步：深呼吸、说出感受、想办法解决。生气时不做决定。' },
  ],
  geography: [
    { k: 'g-direction', t: '方向辨别', p: '太阳从哪边升起？', v: '🌅', a: '东方', o: ['东方', '西方', '南方', '北方'], e: '太阳东升西落，早上对着太阳，前面是东、后面是西。' },
    { k: 'g-direction', t: '指南针', p: '指南针的红色指针通常指向哪里？', v: '🧭', a: '北方', o: ['北方', '南方', '东方', '西方'], e: '指南针红色一头指向北，白色一头指向南。' },
    { k: 'g-direction', t: '位置描述', p: '小红坐在小明的前面，小明坐在小红的？', v: '🪑', a: '后面', o: ['后面', '前面', '左面', '上面'], e: '前面和后面是相对的：小红在前，小明就在后。' },
    { k: 'g-earth', t: '地球常识', p: '我们生活的星球叫什么？', v: '🌍', a: '地球', o: ['地球', '月球', '火星', '太阳'], e: '我们住在地球上，月球绕着地球转，地球绕着太阳转。' },
    { k: 'g-earth', t: '地图常识', p: '地图上通常用蓝色表示什么？', v: '🗺️', a: '水域', o: ['水域', '森林', '沙漠', '高山'], e: '地图上蓝色是江河湖海，绿色是平原，黄色是高原沙漠。' },
    { k: 'g-earth', t: '祖国首都', p: '中国的首都是哪里？', v: '🏙️', a: '北京', o: ['北京', '上海', '广州', '西安'], e: '北京是中国的首都，有天安门、长城和故宫。' },
    { k: 'g-earth', t: '家乡自然', p: '地球表面面积最大的是？', v: '🌊', a: '海洋', o: ['海洋', '陆地', '冰川', '沙漠'], e: '地球表面大部分是海洋，所以地球是蓝色的。' },
    { k: 'g-sky', t: '日月变化', p: '月亮的形状每天都一样吗？', v: '🌙 🌕 🌒', a: '不一样，会变化', o: ['不一样，会变化', '完全一样', '月亮会消失', '月亮是方的'], e: '月亮有圆缺变化：初一弯、十五圆，叫月相变化。' },
    { k: 'g-sky', t: '昼夜交替', p: '天黑了，天上会出现什么？', v: '🌌', a: '月亮和星星', o: ['月亮和星星', '太阳和彩虹', '乌云和闪电', '飞机和风筝'], e: '白天有太阳，夜晚有月亮和星星。' },
    { k: 'geo-10', t: '省会', p: '广东省的省会是？', v: '🏙️', a: '广州', o: ['广州', '深圳', '珠海', '汕头'], e: '广州是广东省会；深圳是经济特区，不是省会。' },
    { k: 'geo-10', t: '省会', p: '四川省的省会是？', v: '🐼', a: '成都', o: ['成都', '重庆', '绵阳', '昆明'], e: '成都是四川省会（大熊猫故乡）；重庆是直辖市。' },
    { k: 'geo-10', t: '名胜', p: '万里长城最著名的关口、登长城常去的是？', v: '🧱', a: '八达岭', o: ['八达岭', '山海关', '嘉峪关', '玉门关'], e: '不到长城非好汉：北京八达岭长城最有名。' },
    { k: 'geo-07', t: '母亲河', p: '长江和黄河都发源于哪个地形区？', v: '🏔️ 🌊', a: '青藏高原', o: ['青藏高原', '内蒙古高原', '黄土高原', '云贵高原'], e: '长江黄河都发源于青藏高原，自西向东流入大海。' },
    { k: 'geo-07', t: '河流', p: '我国最长的河流是？', v: '🌊', a: '长江', o: ['长江', '黄河', '珠江', '黑龙江'], e: '长江全长约6300千米，是我国第一长河；黄河第二长。' },
    { k: 'geo-11', t: '大洲大洋', p: '面积最大的大洲和大洋是？', v: '🌍', a: '亚洲和太平洋', o: ['亚洲和太平洋', '非洲和大西洋', '北美洲和印度洋', '欧洲和北冰洋'], e: '七大洲最大的是亚洲，四大洋最大的是太平洋。' },
    { k: 'geo-11', t: '大洲大洋', p: '四大洋中面积最小的是？', v: '🧊 🌊', a: '北冰洋', o: ['北冰洋', '太平洋', '大西洋', '印度洋'], e: '按面积从大到小：太平洋、大西洋、印度洋、北冰洋。' },
    { k: 'geo-08', t: '气候', p: '我国大部分地区属于哪种气候，夏季高温多雨？', v: '🌧️ ☀️', a: '季风气候', o: ['季风气候', '沙漠气候', '冰原气候', '地中海气候'], e: '季风气候雨热同期，适合水稻生长，但也带来洪涝。' },
    { k: 'geo-09', t: '防灾', p: '地震时正在上课，正确的做法是？', v: '🫨 🏫', a: '躲在课桌下，护住头部', o: ['躲在课桌下，护住头部', '跳楼逃生', '坐电梯下楼', '躲在窗边'], e: '地震三步：伏地、遮挡、手抓牢。护住头颈，摇晃后有序撤离。' },
    { k: 'geo-04', t: '比例尺', p: '地图上 1 厘米代表实际 1 千米，比例尺是？', v: '🗺️', a: '1:100000', o: ['1:100000', '1:1000', '1:10000', '1:10'], e: '1千米=100000厘米，所以比例尺是1:100000。图上1厘米=实际1千米。' },
    { k: 'g-direction', t: '方向辨别', p: '面向北方站立时，右手边是哪一方？', v: '🧭', a: '东方', o: ['东方', '西方', '南方', '北方'], e: '面向北方时，右边是东，左边是西，后面是南。' },
    { k: 'g-direction', t: '方向辨别', p: '太阳落下的方向通常是？', v: '🌇', a: '西方', o: ['西方', '东方', '南方', '北方'], e: '太阳东升西落，傍晚太阳落在西边。' },
    { k: 'g-earth', t: '地图常识', p: '地图上的图例有什么作用？', v: '🗺️', a: '帮助看懂地图符号', o: ['帮助看懂地图符号', '表示天气变化', '计算年龄', '测量体重'], e: '图例像地图的说明书，告诉我们各种符号代表什么。' },
    { k: 'g-sky', t: '昼夜交替', p: '白天和黑夜交替出现，主要是因为？', v: '🌞 🌙', a: '地球自转', o: ['地球自转', '月亮变大', '云在移动', '太阳熄灭'], e: '地球不停自转，被太阳照到的一面是白天，背向太阳的一面是夜晚。' },
    { k: 'g-sky', t: '日月星空', p: '月亮会发光吗？', v: '🌙', a: '不会，反射太阳光', o: ['不会，反射太阳光', '会像太阳一样发光', '只在白天发光', '靠星星供电'], e: '月亮本身不发光，我们看到的是它反射的太阳光。' },
    { k: 'geo-04', t: '地图方向', p: '在通常的地图上，上方表示哪个方向？', v: '🗺️ ⬆️', a: '北方', o: ['北方', '南方', '东方', '西方'], e: '没有特别说明时，地图通常“上北下南、左西右东”。' },
    { k: 'geo-04', t: '比例尺', p: '地图比例尺 1:500000，图上 1 厘米表示实际多少千米？', v: '📏', a: '5千米', o: ['5千米', '500千米', '50千米', '0.5千米'], e: '500000厘米等于5千米，所以图上1厘米代表实际5千米。' },
    { k: 'geo-04', t: '地形图', p: '等高线越密集的地方，说明地形通常？', v: '⛰️', a: '坡度越陡', o: ['坡度越陡', '越平坦', '一定是海洋', '没有高度变化'], e: '等高线越密，表示相同高度差内距离越短，坡就越陡。' },
    { k: 'geo-05', t: '中国疆域', p: '我国面积最大的省级行政区是？', v: '🏜️', a: '新疆维吾尔自治区', o: ['新疆维吾尔自治区', '四川省', '广东省', '江苏省'], e: '新疆位于我国西北部，是我国面积最大的省级行政区。' },
    { k: 'geo-05', t: '省会', p: '云南省的省会是？', v: '🌸', a: '昆明', o: ['昆明', '贵阳', '南宁', '成都'], e: '昆明是云南省省会，四季如春。' },
    { k: 'geo-05', t: '省会', p: '陕西省的省会是？', v: '🏛️', a: '西安', o: ['西安', '兰州', '太原', '郑州'], e: '西安是陕西省省会，也是著名的历史文化名城。' },
    { k: 'geo-06', t: '地形地貌', p: '我国地势的总体特点是？', v: '🏔️', a: '西高东低，呈阶梯状', o: ['西高东低，呈阶梯状', '东高西低', '南高北低', '四周高中间低'], e: '我国地势西部高、东部低，像三级台阶，许多河流向东流。' },
    { k: 'geo-06', t: '地形地貌', p: '“世界屋脊”通常指哪一地形区？', v: '🏔️', a: '青藏高原', o: ['青藏高原', '东北平原', '四川盆地', '东南丘陵'], e: '青藏高原平均海拔很高，因此被称为“世界屋脊”。' },
    { k: 'geo-06', t: '地形地貌', p: '“鱼米之乡”常用来称呼哪一地区？', v: '🌾 🐟', a: '长江中下游平原', o: ['长江中下游平原', '青藏高原', '塔里木盆地', '内蒙古高原'], e: '长江中下游平原地势平坦、水网密布，盛产稻米和水产品。' },
    { k: 'geo-07', t: '河流', p: '黄河最终注入哪个海？', v: '🌊', a: '渤海', o: ['渤海', '黄海', '东海', '南海'], e: '黄河从西向东流，最后注入渤海。' },
    { k: 'geo-07', t: '河流', p: '长江最终注入哪个海？', v: '🚢', a: '东海', o: ['东海', '渤海', '黄海', '南海'], e: '长江流经上海附近，最终注入东海。' },
    { k: 'geo-07', t: '河流保护', p: '治理黄河水土流失的重要措施是？', v: '🌳 🌊', a: '植树种草，保持水土', o: ['植树种草，保持水土', '砍伐森林', '把垃圾倒入河中', '堵住所有支流'], e: '植树种草能减少水土流失，保护黄河需要大家共同努力。' },
    { k: 'geo-08', t: '气候', p: '我国东部季风区夏季的主要特点是？', v: '☀️ 🌧️', a: '高温多雨', o: ['高温多雨', '寒冷干燥', '全年无雨', '全年下雪'], e: '夏季风带来温暖湿润的空气，所以东部夏季通常高温多雨。' },
    { k: 'geo-08', t: '气候', p: '我国南方比北方冬季温暖，主要影响因素是？', v: '🌡️', a: '纬度位置', o: ['纬度位置', '离月亮远近', '城市人口多少', '地图颜色'], e: '我国南北跨度大，南方纬度低，冬季获得的太阳热量较多。' },
    { k: 'geo-09', t: '防灾', p: '台风来临前，正确的做法是？', v: '🌀', a: '关好门窗，关注预警信息', o: ['关好门窗，关注预警信息', '到海边看大浪', '站在广告牌下', '打开所有窗户'], e: '台风天要留在安全室内，远离海边、树木和广告牌。' },
    { k: 'geo-03', t: '经纬线', p: '赤道把地球分成哪两个半球？', v: '🌍', a: '北半球和南半球', o: ['北半球和南半球', '东半球和西半球', '陆半球和水半球', '昼半球和夜半球'], e: '赤道是最大的纬线圈，把地球分为北半球和南半球。' },
    { k: 'geo-03', t: '经纬线', p: '本初子午线的经度是？', v: '🌐', a: '0°', o: ['0°', '90°', '180°', '23.5°'], e: '本初子午线被定为0°经线。' },
    { k: 'geo-11', t: '大洲大洋', p: '世界上面积最小的大洲是？', v: '🗺️', a: '大洋洲', o: ['大洋洲', '欧洲', '南美洲', '南极洲'], e: '七大洲中面积最小的是大洋洲。' },
    { k: 'geo-11', t: '大洲位置', p: '中国位于亚洲的哪个部位？', v: '🌏', a: '东部', o: ['东部', '西部', '南部', '中部'], e: '中国位于亚洲东部、太平洋西岸。' },
    { k: 'geo-12', t: '世界国家', p: '日本是一个怎样的国家？', v: '🇯🇵', a: '岛国', o: ['岛国', '内陆国', '没有海岸线的国家', '沙漠国家'], e: '日本由许多岛屿组成，四面环海，是岛国。' },
    { k: 'geo-12', t: '世界国家', p: '埃及的金字塔位于哪一洲？', v: '🔺', a: '非洲', o: ['非洲', '欧洲', '亚洲', '南美洲'], e: '埃及位于非洲东北部。' },
    { k: 'geo-12', t: '世界国家', p: '巴西主要位于哪个大洲？', v: '🇧🇷', a: '南美洲', o: ['南美洲', '北美洲', '非洲', '欧洲'], e: '巴西位于南美洲东部。' },
    { k: 'geo-12', t: '世界国家', p: '俄罗斯地跨哪两个大洲？', v: '🇷🇺', a: '亚洲和欧洲', o: ['亚洲和欧洲', '非洲和欧洲', '亚洲和非洲', '北美洲和亚洲'], e: '俄罗斯国土横跨亚洲和欧洲。' },
    { k: 'geo-08', t: '气候带', p: '赤道附近的气候通常有什么特点？', v: '🌴 🌧️', a: '全年高温多雨', o: ['全年高温多雨', '全年寒冷少雨', '四季都下雪', '昼夜都没有变化'], e: '赤道附近通常全年高温多雨。' },
    { k: 'geo-09', t: '防灾', p: '发生洪水时，应该向哪里转移？', v: '🌧️ 🏃', a: '地势较高且安全的地方', o: ['地势较高且安全的地方', '河道中央', '地下通道', '低洼停车场'], e: '洪水来时要向高处转移，远离河道和低洼地。' },
  ],
};